#pragma only_renderers d3d11 playstation xboxone xboxseries vulkan metal switch switch2

#pragma kernel ScreenSpaceMultipleScattering

#include "Packages/com.vivid.render-pipelines/Shaders/Core/Public/Core.hlsl"

// #pragma enable_d3d11_debug_symbols

TEXTURE2D(_OpticalFogTransmittance);
TEXTURE2D(_ColorPyramidTexture);
RW_TEXTURE2D(float4, _Destination);
float _MultipleScatteringIntensity;
uint _OpticalFogTextureChannel;

[numthreads(8, 8, 1)]
void ScreenSpaceMultipleScattering(uint3 dispatchThreadId : SV_DispatchThreadID)
{
    uint2 pixelPosition = dispatchThreadId.xy;
    float2 centerPixel = pixelPosition + 0.5;
    float2 uv = centerPixel * _ScreenSize.zw;

    float2 opticalFogTransmittanceData = SAMPLE_TEXTURE2D_X_LOD(_OpticalFogTransmittance, sampler_TrilinearClamp, uv * _RTHandleScale.xy, 0).xy;
    // When lens flare are enabled, the SSMS opacity is stored in the green channel, because we don't want cloud opacity in this pass.
    float opticalFogTransmittance = 1 - saturate(opticalFogTransmittanceData[_OpticalFogTextureChannel]);
    _Destination[(pixelPosition)] = SAMPLE_TEXTURE2D_X_LOD(_ColorPyramidTexture, sampler_TrilinearClamp, uv * _RTHandleScale.xy, opticalFogTransmittance * _MultipleScatteringIntensity);
}
