
#pragma kernel BilateralFilterH         SHADOW_BILATERAL_FILTER     BILATERAL_FILTER=BilateralFilterH
#pragma kernel BilateralFilterV         SHADOW_BILATERAL_FILTER     BILATERAL_FILTER=BilateralFilterV       FINAL_PASS


#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Shaders/Utils/Deferred.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Extension/Shadow/ShadowsPCSS.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareNormalsTexture.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Extension/TileClassify.hlsl"


groupshared float4 localNormalDepth[256];
groupshared float localColor[256];

struct CoordData {
    float3  normal;
    float   depth;
    float   color;
};


RW_TEXTURE2D(float, _BilateralTexture);


#define GAUSSIAN_WEIGHT_COUNT (9)
static const float gaussianWeight[GAUSSIAN_WEIGHT_COUNT] = {0.02763055, 0.06628224, 0.1238315, 0.1801738, 0.2041637, 0.1801738, 0.1238315, 0.06628224, 0.02763055};
RWStructuredBuffer<uint> g_TileList;

#define SCREENSPACE_SHADOWS_TILE_SIZE   (16)
#define SCREENSPACE_SHADOWS_GROUP_SIZE  (SCREENSPACE_SHADOWS_TILE_SIZE / 2)
#define SCREENSPACE_SHADOWS_THREADS     (64)

void InitializeDispatchThreadIdFromTileList(uint groupId, uint2 gThreadId, out uint2 tileCoord, out uint2 dThreadId)
{
    uint encodedTileIndex = g_TileList[groupId / 4];

    tileCoord = DecodeTileIndex(encodedTileIndex);
    dThreadId = tileCoord * SCREENSPACE_SHADOWS_TILE_SIZE
        + uint2(groupId & 1, (groupId >> 1) & 1) * SCREENSPACE_SHADOWS_GROUP_SIZE
        + gThreadId;
}

struct BilateralData
{
    float3 position;
    float depth;
    float3 normal;
};

float GetEdegStoppingNormalWeight(float3 normal1, float3 normal2)
{
    return pow(max(dot(normal1, normal2), 0.0f), 32.0f);
}

float GetEdgeStoppingDepthWeight(float centerDepth, float neighDepth)
{
    return exp(-abs(centerDepth - neighDepth) * 4.0);
}

// TODO: Actually we should use plane base depth weight like SVGF.
float ComputeBilateralWeight(BilateralData center, BilateralData neigh)
{
    // Depth
    float depthWeight = GetEdgeStoppingDepthWeight(center.depth, neigh.depth);

    // Normal
    float normalWeight = GetEdegStoppingNormalWeight(center.normal, neigh.normal);

    return depthWeight * normalWeight;
}

CoordData LoadFromGroupSharedMemory(uint2 gThreadId)
{
    #if FINAL_PASS
    gThreadId.y += 4;
    #else
    gThreadId.x += 4;
    #endif

    uint localID = gThreadId.x + 16 * gThreadId.y;
    float4 encodedNormalDepth = localNormalDepth[localID];

    CoordData neighborSample;
    ZERO_INITIALIZE(CoordData, neighborSample);
    neighborSample.normal = encodedNormalDepth.xyz;
    neighborSample.depth = encodedNormalDepth.w;
    neighborSample.color = localColor[localID];
    
    return neighborSample;
}

void StoreInGroupSharedMemory(uint2 gThreadId, CoordData inData)
{
    #if FINAL_PASS
    gThreadId.y += 4;
    #else
    gThreadId.x += 4;
    #endif

    uint localID = gThreadId.x + 16 * gThreadId.y;
    localNormalDepth[localID] = float4(inData.normal.xyz, inData.depth);
    localColor[localID] = inData.color;
}

void LoadCoordData(int2 coordSS, out CoordData outData)
{
    ZERO_INITIALIZE(CoordData, outData);
    if (coordSS.x >= _ScreenSize.x || coordSS.y >= _ScreenSize.y || coordSS.x < 0.0 || coordSS.y < 0.0)
    {
        outData.depth = UNITY_RAW_FAR_CLIP_VALUE;
        return;
    }

    float deviceDepth = LoadSceneDepth(coordSS);
    if (deviceDepth == UNITY_RAW_FAR_CLIP_VALUE)
    {
        outData.depth = UNITY_RAW_FAR_CLIP_VALUE;
        return;
    }

    float3 normalWS = normalize(LoadSceneNormals(coordSS));

    outData.normal = normalWS;
    outData.depth = LinearEyeDepth(deviceDepth, _ZBufferParams);
    outData.color = _BilateralTexture[coordSS];
}

void InitializeGroupSharedMemory(uint2 dThreadId, uint2 gThreadId)
{
    #if FINAL_PASS
    uint2 offset[2] = {uint2(0, -4), uint2(0, 4)};
    #else
    uint2 offset[2] = {uint2(-4, 0), uint2(4, 0)};
    #endif

    CoordData coordData[2];
    for (int i = 0; i < 2; i++)
    {
        LoadCoordData(dThreadId + offset[i], coordData[i]);
    }

    for (int j = 0; j < 2; j++)
    {
        StoreInGroupSharedMemory(gThreadId + offset[j], coordData[j]);
    }
}



[numthreads(SCREENSPACE_SHADOWS_GROUP_SIZE, SCREENSPACE_SHADOWS_GROUP_SIZE, 1)]
void BILATERAL_FILTER(uint3 dispatchThreadId : SV_DispatchThreadID, uint2 groupThreadId : SV_GroupThreadID, uint groupId : SV_GroupID)
{
    uint2 coordSS;
    uint2 tileCoord;
    InitializeDispatchThreadIdFromTileList(groupId, groupThreadId, tileCoord, coordSS);

    uint2 coordGroup = groupThreadId.xy;
    InitializeGroupSharedMemory(coordSS, coordGroup);

    GroupMemoryBarrierWithGroupSync();

    CoordData center = LoadFromGroupSharedMemory(coordGroup);
    float2 screenUV = coordSS * _ScreenSize.zw + (0.5 * _ScreenSize.zw);

    if (center.depth == UNITY_RAW_FAR_CLIP_VALUE)
        return;

    // Position
    PositionInputs posInput = GetPositionInput(coordSS.xy, _ScreenSize.zw, center.depth, UNITY_MATRIX_I_VP, UNITY_MATRIX_V, uint2(0, 0));

    BilateralData centerData;
    ZERO_INITIALIZE(BilateralData, centerData);
    {
        centerData.normal = center.normal;
        centerData.depth = center.depth;
    }


    float colorSum = center.color * gaussianWeight[4];
    float weightSum = gaussianWeight[4];

    // TODO: Actually far distance pixels should have smaller radius.
    int radius = 4;

    #if FINAL_PASS
        const int2 passIncr = int2(0, 1);
    #else
        const int2 passIncr = int2(1, 0);
    #endif

    int2 neighCoordGroup = coordGroup - radius * passIncr;
    for (int r = -radius; r <= radius; r++, neighCoordGroup += passIncr)
    {
        if (r == 0)
            continue;
        CoordData neigh = LoadFromGroupSharedMemory(neighCoordGroup);
        if (neigh.depth == UNITY_RAW_FAR_CLIP_VALUE)
            continue;

        BilateralData neighData;
        ZERO_INITIALIZE(BilateralData, neighData);
        {
            neighData.normal = neigh.normal;
            neighData.depth = neigh.depth;
        }

        float bilateralWeight = ComputeBilateralWeight(centerData, neighData);
        float weight = gaussianWeight[r + 4] * bilateralWeight;

        colorSum += weight * neigh.color;
        weightSum += weight;
    }

    _BilateralTexture[coordSS] = colorSum / weightSum;
}
