using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.Callbacks;
using UnityEditor.Compilation;
using UnityEngine;
using VividRP.Runtime;

namespace VividRP.Editor
{
    internal static class VividPerObjectLayoutGenerator
    {
        private const string GeneratedRelativePath =
            "Shaders/Core/Public/PerObjectBufferLayouts.generated.hlsl";

        private const string PublicIncludePath =
            "Packages/com.vivid.render-pipelines/Shaders/Core/Public/PerObjectBuffer.hlsl";
        private const string GeneratedHeader = "// <auto-generated by VividPerObjectLayoutGenerator>";

        private static bool s_IsGenerating;

        internal static string GeneratedPath =>
            VividPackagePathUtility.GetPreferredAssetPath(GeneratedRelativePath);

        internal static string GenerateAll()
        {
            return Generate(DiscoverLayouts(), GeneratedPath);
        }

        internal static string Generate(
            IReadOnlyList<VividPerObjectLayout> layouts,
            string generatedPath)
        {
            if (layouts == null)
                throw new ArgumentNullException(nameof(layouts));
            if (string.IsNullOrEmpty(generatedPath))
                throw new ArgumentException("A generated HLSL path is required.", nameof(generatedPath));
            if (s_IsGenerating)
                return generatedPath;

            s_IsGenerating = true;
            try
            {
                string source = BuildSource(layouts);
                string directory = Path.GetDirectoryName(generatedPath);
                if (!string.IsNullOrEmpty(directory))
                    Directory.CreateDirectory(directory);

                bool sourceChanged = !File.Exists(generatedPath)
                    || !string.Equals(File.ReadAllText(generatedPath), source, StringComparison.Ordinal);
                if (sourceChanged)
                {
                    File.WriteAllText(
                        generatedPath,
                        source,
                        new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
                    AssetDatabase.ImportAsset(generatedPath, ImportAssetOptions.ForceSynchronousImport);
                }

                return generatedPath;
            }
            finally
            {
                s_IsGenerating = false;
            }
        }

        internal static bool IsSynchronized(
            IReadOnlyList<VividPerObjectLayout> layouts,
            string generatedPath)
        {
            if (layouts == null || string.IsNullOrEmpty(generatedPath) || !File.Exists(generatedPath))
                return false;

            try
            {
                return string.Equals(
                    File.ReadAllText(generatedPath),
                    BuildSource(layouts),
                    StringComparison.Ordinal);
            }
            catch (Exception)
            {
                return false;
            }
        }

        internal static IReadOnlyList<VividPerObjectLayout> DiscoverLayouts()
        {
            var playerAssemblyNames = new HashSet<string>(
                CompilationPipeline.GetAssemblies(AssembliesType.Player).Select(assembly => assembly.name),
                StringComparer.Ordinal);
            var layoutTypes = new List<Type>();
            foreach (Type type in TypeCache.GetTypesDerivedFrom<VividPerObjectLayout>())
            {
                if (type.IsAbstract || type.ContainsGenericParameters)
                    continue;
                if (!playerAssemblyNames.Contains(type.Assembly.GetName().Name))
                    continue;
                layoutTypes.Add(type);
            }

            layoutTypes.Sort(static (left, right) =>
                string.CompareOrdinal(left.FullName, right.FullName));
            var layouts = new List<VividPerObjectLayout>(layoutTypes.Count);
            for (int i = 0; i < layoutTypes.Count; i++)
                layouts.Add(VividPerObjectLayout.GetShared(layoutTypes[i]));
            return layouts;
        }

        internal static string BuildSource(IReadOnlyList<VividPerObjectLayout> layouts)
        {
            if (layouts == null)
                throw new ArgumentNullException(nameof(layouts));

            var sortedLayouts = new List<VividPerObjectLayout>(layouts.Count);
            var identifiers = new Dictionary<string, Type>(StringComparer.Ordinal);
            for (int i = 0; i < layouts.Count; i++)
            {
                VividPerObjectLayout layout = layouts[i]
                    ?? throw new InvalidOperationException($"Layout collection contains null at index {i}.");
                layout.Validate();
                if (identifiers.TryGetValue(layout.ShaderIdentifier, out Type existingType))
                {
                    throw new InvalidOperationException(
                        $"Per-object layouts '{existingType.FullName}' and '{layout.GetType().FullName}' " +
                        $"both use ShaderIdentifier '{layout.ShaderIdentifier}'.");
                }

                identifiers.Add(layout.ShaderIdentifier, layout.GetType());
                sortedLayouts.Add(layout);
            }

            sortedLayouts.Sort(static (left, right) =>
            {
                int identifierComparison = string.CompareOrdinal(left.ShaderIdentifier, right.ShaderIdentifier);
                return identifierComparison != 0
                    ? identifierComparison
                    : string.CompareOrdinal(left.GetType().FullName, right.GetType().FullName);
            });

            var builder = new StringBuilder(Math.Max(4096, sortedLayouts.Count * 2048));
            builder.AppendLine(GeneratedHeader);
            builder.AppendLine("// Generated from VividPerObjectLayout types in Player assemblies; do not edit.");
            builder.AppendLine("#ifndef VIVID_PER_OBJECT_LAYOUTS_GENERATED_INCLUDED");
            builder.AppendLine("#define VIVID_PER_OBJECT_LAYOUTS_GENERATED_INCLUDED");
            builder.AppendLine();
            builder.Append("#include \"").Append(PublicIncludePath).AppendLine("\"");
            builder.AppendLine();

            for (int i = 0; i < sortedLayouts.Count; i++)
                AppendLayout(builder, sortedLayouts[i]);

            if (sortedLayouts.Count == 0)
                builder.AppendLine("// No concrete VividPerObjectLayout types were discovered.");

            builder.AppendLine("#endif");
            return builder.ToString().Replace("\r\n", "\n");
        }

        private static void AppendLayout(StringBuilder builder, VividPerObjectLayout layout)
        {
            string identifier = layout.ShaderIdentifier;
            builder.Append("// ").Append(layout.GetType().FullName).AppendLine();
            builder.Append("#if defined(VIVID_PER_OBJECT_LAYOUT_").Append(identifier).AppendLine(")");
            builder.Append("#define VIVID_PER_OBJECT_").Append(identifier).Append("_SIGNATURE 0x")
                .Append(layout.Signature.ToString("X8")).AppendLine("u");
            builder.Append("#define VIVID_PER_OBJECT_").Append(identifier).Append("_STRIDE ")
                .Append(layout.RecordStride).AppendLine("u");
            builder.Append("static VividPerObjectContext VividPerObjectContext_")
                .Append(identifier).AppendLine(";");
            builder.Append("#define VIVID_SETUP_PER_OBJECT_").Append(identifier).Append("() \\")
                .AppendLine();
            builder.Append("    VividPerObjectContext_").Append(identifier)
                .Append(" = VividPerObjectCreateContext(VIVID_PER_OBJECT_")
                .Append(identifier).AppendLine("_SIGNATURE)");
            builder.AppendLine();

            IReadOnlyList<VividPerObjectLayout.PackedProperty> properties = layout.PackedProperties;
            for (int i = 0; i < properties.Count; i++)
                AppendAccessor(builder, identifier, properties[i]);

            builder.AppendLine("#if !defined(VIVID_PER_OBJECT_NO_PROPERTY_ALIASES)");
            builder.AppendLine("    #if defined(VIVID_PER_OBJECT_LAYOUT_ALIASES_SELECTED)");
            builder.AppendLine("        #error Only one VIVID_PER_OBJECT_LAYOUT_<Identifier> may enable property aliases per shader program.");
            builder.AppendLine("    #endif");
            builder.AppendLine("    #define VIVID_PER_OBJECT_LAYOUT_ALIASES_SELECTED 1");
            for (int i = 0; i < properties.Count; i++)
            {
                VividPerObjectLayout.PackedProperty property = properties[i];
                builder.Append("    #define ").Append(property.Definition.Name).Append(' ')
                    .Append(GetAccessorName(identifier, property.Definition.Name)).AppendLine("()");
            }
            builder.AppendLine("#endif");
            builder.AppendLine("#endif");
            builder.AppendLine();
        }

        private static void AppendAccessor(
            StringBuilder builder,
            string identifier,
            VividPerObjectLayout.PackedProperty property)
        {
            VividPerObjectPropertyDefinition definition = property.Definition;
            string accessorName = GetAccessorName(identifier, definition.Name);
            string contextName = $"VividPerObjectContext_{identifier}";
            string offset = property.Offset + "u";

            switch (property.Type)
            {
                case VividPerObjectPropertyType.Int:
                    builder.Append("int ").Append(accessorName).AppendLine("()");
                    builder.AppendLine("{");
                    builder.Append("    return VividPerObjectLoadInt(").Append(contextName).Append(", ")
                        .Append(offset).Append(", ").Append(FormatInt(definition.IntDefault)).AppendLine(");");
                    builder.AppendLine("}");
                    break;
                case VividPerObjectPropertyType.Float:
                    builder.Append("float ").Append(accessorName).AppendLine("()");
                    builder.AppendLine("{");
                    builder.Append("    return VividPerObjectLoadFloat(").Append(contextName).Append(", ")
                        .Append(offset).Append(", ").Append(FormatFloat(definition.FloatDefault)).AppendLine(");");
                    builder.AppendLine("}");
                    break;
                case VividPerObjectPropertyType.Vector:
                    builder.Append("float4 ").Append(accessorName).AppendLine("()");
                    builder.AppendLine("{");
                    builder.Append("    return VividPerObjectLoadFloat4(").Append(contextName).Append(", ")
                        .Append(offset).Append(", ").Append(FormatVector(definition.VectorDefault)).AppendLine(");");
                    builder.AppendLine("}");
                    break;
                case VividPerObjectPropertyType.Color:
                    builder.Append("float4 ").Append(accessorName).AppendLine("()");
                    builder.AppendLine("{");
                    Color color = definition.ColorDefault;
                    builder.Append("    return VividPerObjectLoadFloat4(").Append(contextName).Append(", ")
                        .Append(offset).Append(", ")
                        .Append(FormatVector(new Vector4(color.r, color.g, color.b, color.a))).AppendLine(");");
                    builder.AppendLine("}");
                    break;
                case VividPerObjectPropertyType.Matrix:
                    builder.Append("float4x4 ").Append(accessorName).AppendLine("()");
                    builder.AppendLine("{");
                    builder.Append("    return VividPerObjectLoadFloat4x4(").Append(contextName).Append(", ")
                        .Append(offset).Append(", ").Append(FormatMatrix(definition.MatrixDefault)).AppendLine(");");
                    builder.AppendLine("}");
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
            builder.AppendLine();
        }

        private static string GetAccessorName(string identifier, string propertyName)
        {
            return $"VividPerObject_{identifier}_Get_{propertyName}";
        }

        private static string FormatInt(int value)
        {
            return $"asint(0x{unchecked((uint)value):X8}u)";
        }

        private static string FormatFloat(float value)
        {
            return $"asfloat(0x{unchecked((uint)BitConverter.SingleToInt32Bits(value)):X8}u)";
        }

        private static string FormatVector(Vector4 value)
        {
            return $"float4({FormatFloat(value.x)}, {FormatFloat(value.y)}, {FormatFloat(value.z)}, {FormatFloat(value.w)})";
        }

        private static string FormatMatrix(Matrix4x4 value)
        {
            var builder = new StringBuilder(512);
            builder.Append("float4x4(");
            for (int row = 0; row < 4; row++)
            {
                if (row > 0)
                    builder.Append(", ");
                builder.Append("float4(");
                for (int column = 0; column < 4; column++)
                {
                    if (column > 0)
                        builder.Append(", ");
                    builder.Append(FormatFloat(value[row, column]));
                }
                builder.Append(')');
            }
            builder.Append(')');
            return builder.ToString();
        }
    }

    [InitializeOnLoad]
    internal static class VividPerObjectLayoutGenerationBootstrap
    {
        static VividPerObjectLayoutGenerationBootstrap()
        {
            EditorApplication.delayCall += Generate;
        }

        [DidReloadScripts]
        private static void OnScriptsReloaded()
        {
            EditorApplication.delayCall += Generate;
        }

        private static void Generate()
        {
            try
            {
                VividPerObjectLayoutGenerator.GenerateAll();
            }
            catch (Exception exception)
            {
                Debug.LogException(exception);
            }
        }
    }

    internal sealed class VividPerObjectLayoutBuildPreprocessor : IPreprocessBuildWithReport
    {
        public int callbackOrder => 0;

        public void OnPreprocessBuild(BuildReport report)
        {
            try
            {
                VividPerObjectLayoutGenerator.GenerateAll();
            }
            catch (Exception exception)
            {
                throw new BuildFailedException(
                    $"Failed to generate Vivid per-object layout HLSL: {exception.Message}");
            }
        }
    }
}
