using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;
using VividRP.Runtime;

namespace VividRP.Editor
{
    internal static class VividPerObjectLayoutGenerator
    {
        private const string GeneratedSuffix = ".generated.hlsl";
        private const string PublicIncludePath =
            "Packages/com.vivid.render-pipelines/Shaders/Core/Public/PerObjectBuffer.hlsl";
        private const string GeneratedHeader = "// <auto-generated by VividPerObjectLayoutGenerator>";

        private static bool s_IsGenerating;

        internal static string Generate(VividPerObjectLayout layout)
        {
            if (layout == null)
                throw new ArgumentNullException(nameof(layout));

            string layoutPath = AssetDatabase.GetAssetPath(layout);
            if (string.IsNullOrEmpty(layoutPath))
                throw new InvalidOperationException("Save the VividPerObjectLayout as an asset before generating HLSL.");

            layout.ValidateAndRebuild();
            string generatedPath = GetGeneratedPath(layoutPath);
            string source = BuildSource(layout, layoutPath);
            string previousGeneratedPath = layout.GeneratedIncludePath;

            if (!string.IsNullOrEmpty(previousGeneratedPath)
                && !string.Equals(previousGeneratedPath, generatedPath, StringComparison.Ordinal)
                && IsOwnedGeneratedFile(previousGeneratedPath))
            {
                AssetDatabase.DeleteAsset(previousGeneratedPath);
            }

            string directory = Path.GetDirectoryName(generatedPath);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            bool sourceChanged = !File.Exists(generatedPath)
                || !string.Equals(File.ReadAllText(generatedPath), source, StringComparison.Ordinal);
            if (sourceChanged)
                File.WriteAllText(generatedPath, source, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

            if (!string.Equals(layout.GeneratedIncludePath, generatedPath, StringComparison.Ordinal))
            {
                layout.SetGeneratedIncludePath(generatedPath);
                EditorUtility.SetDirty(layout);
                AssetDatabase.SaveAssetIfDirty(layout);
            }

            if (sourceChanged)
                AssetDatabase.ImportAsset(generatedPath, ImportAssetOptions.ForceSynchronousImport);

            return generatedPath;
        }

        internal static void GenerateAll()
        {
            if (s_IsGenerating)
                return;

            s_IsGenerating = true;
            try
            {
                string[] layoutGuids = AssetDatabase.FindAssets("t:VividPerObjectLayout");
                for (int i = 0; i < layoutGuids.Length; i++)
                {
                    string path = AssetDatabase.GUIDToAssetPath(layoutGuids[i]);
                    VividPerObjectLayout layout = AssetDatabase.LoadAssetAtPath<VividPerObjectLayout>(path);
                    if (layout != null)
                        Generate(layout);
                }
            }
            finally
            {
                s_IsGenerating = false;
            }
        }

        internal static bool IsSynchronized(VividPerObjectLayout layout)
        {
            if (layout == null)
                return false;

            string layoutPath = AssetDatabase.GetAssetPath(layout);
            if (string.IsNullOrEmpty(layoutPath))
                return false;

            try
            {
                layout.ValidateAndRebuild();
                string generatedPath = GetGeneratedPath(layoutPath);
                return string.Equals(layout.GeneratedIncludePath, generatedPath, StringComparison.Ordinal)
                    && File.Exists(generatedPath)
                    && string.Equals(
                        File.ReadAllText(generatedPath),
                        BuildSource(layout, layoutPath),
                        StringComparison.Ordinal);
            }
            catch (Exception)
            {
                return false;
            }
        }

        internal static string BuildSource(VividPerObjectLayout layout, string layoutPath = null)
        {
            if (layout == null)
                throw new ArgumentNullException(nameof(layout));

            layout.ValidateAndRebuild();
            string identifier = layout.ShaderIdentifier;
            string signatureHex = layout.Signature.ToString("X8");
            string uniqueName = $"{identifier}_{signatureHex}";
            var builder = new StringBuilder(4096);
            builder.AppendLine(GeneratedHeader);
            builder.Append("// Source: ").AppendLine(layoutPath ?? AssetDatabase.GetAssetPath(layout));
            builder.AppendLine("// Regenerate from the VividPerObjectLayout asset; do not edit this file.");
            builder.Append("#ifndef VIVID_PER_OBJECT_LAYOUT_")
                .Append(identifier.ToUpperInvariant())
                .Append('_')
                .Append(signatureHex)
                .AppendLine("_INCLUDED");
            builder.Append("#define VIVID_PER_OBJECT_LAYOUT_")
                .Append(identifier.ToUpperInvariant())
                .Append('_')
                .Append(signatureHex)
                .AppendLine("_INCLUDED");
            builder.AppendLine();
            builder.Append("#include \"").Append(PublicIncludePath).AppendLine("\"");
            builder.AppendLine();
            builder.Append("#define VIVID_PER_OBJECT_").Append(identifier).Append("_SIGNATURE 0x")
                .Append(signatureHex).AppendLine("u");
            builder.Append("#define VIVID_PER_OBJECT_").Append(identifier).Append("_STRIDE ")
                .Append(layout.RecordStride).AppendLine("u");
            builder.Append("static VividPerObjectContext VividPerObjectContext_").Append(uniqueName).AppendLine(";");
            builder.Append("#define VIVID_SETUP_PER_OBJECT_").Append(identifier).Append("() \\")
                .AppendLine();
            builder.Append("    VividPerObjectContext_").Append(uniqueName)
                .Append(" = VividPerObjectCreateContext(VIVID_PER_OBJECT_")
                .Append(identifier).AppendLine("_SIGNATURE)");
            builder.AppendLine();

            IReadOnlyList<VividPerObjectLayout.PackedProperty> properties = layout.PackedProperties;
            for (int i = 0; i < properties.Count; i++)
            {
                VividPerObjectLayout.PackedProperty property = properties[i];
                AppendAccessor(builder, uniqueName, property);
            }

            builder.AppendLine("#ifndef VIVID_PER_OBJECT_NO_PROPERTY_ALIASES");
            for (int i = 0; i < properties.Count; i++)
            {
                VividPerObjectLayout.PackedProperty property = properties[i];
                builder.Append("#define ").Append(property.Definition.Name).Append(' ')
                    .Append(GetAccessorName(uniqueName, property.Definition.Name)).AppendLine("()");
            }
            builder.AppendLine("#endif");
            builder.AppendLine();
            builder.AppendLine("#endif");
            return builder.ToString().Replace("\r\n", "\n");
        }

        internal static string GetGeneratedPath(string layoutPath)
        {
            if (string.IsNullOrEmpty(layoutPath))
                throw new ArgumentException("A layout asset path is required.", nameof(layoutPath));
            return Path.ChangeExtension(layoutPath, null) + GeneratedSuffix;
        }

        internal static void DeleteGeneratedForDeletedLayout(string layoutPath)
        {
            if (string.IsNullOrEmpty(layoutPath)
                || !string.Equals(Path.GetExtension(layoutPath), ".asset", StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            string generatedPath = GetGeneratedPath(layoutPath);
            if (IsOwnedGeneratedFile(generatedPath))
                AssetDatabase.DeleteAsset(generatedPath);
        }

        private static void AppendAccessor(
            StringBuilder builder,
            string uniqueName,
            VividPerObjectLayout.PackedProperty property)
        {
            VividPerObjectPropertyDefinition definition = property.Definition;
            string accessorName = GetAccessorName(uniqueName, definition.Name);
            string contextName = $"VividPerObjectContext_{uniqueName}";
            string offset = property.Offset + "u";

            switch (property.Type)
            {
                case VividPerObjectPropertyType.Int:
                    builder.Append("int ").Append(accessorName).AppendLine("()");
                    builder.AppendLine("{");
                    builder.Append("    return VividPerObjectLoadInt(").Append(contextName).Append(", ")
                        .Append(offset).Append(", ").Append(FormatInt(definition.IntDefault)).AppendLine(");");
                    builder.AppendLine("}");
                    break;
                case VividPerObjectPropertyType.Float:
                    builder.Append("float ").Append(accessorName).AppendLine("()");
                    builder.AppendLine("{");
                    builder.Append("    return VividPerObjectLoadFloat(").Append(contextName).Append(", ")
                        .Append(offset).Append(", ").Append(FormatFloat(definition.FloatDefault)).AppendLine(");");
                    builder.AppendLine("}");
                    break;
                case VividPerObjectPropertyType.Vector:
                    builder.Append("float4 ").Append(accessorName).AppendLine("()");
                    builder.AppendLine("{");
                    builder.Append("    return VividPerObjectLoadFloat4(").Append(contextName).Append(", ")
                        .Append(offset).Append(", ").Append(FormatVector(definition.VectorDefault)).AppendLine(");");
                    builder.AppendLine("}");
                    break;
                case VividPerObjectPropertyType.Color:
                    builder.Append("float4 ").Append(accessorName).AppendLine("()");
                    builder.AppendLine("{");
                    Color color = definition.ColorDefault;
                    builder.Append("    return VividPerObjectLoadFloat4(").Append(contextName).Append(", ")
                        .Append(offset).Append(", ")
                        .Append(FormatVector(new Vector4(color.r, color.g, color.b, color.a))).AppendLine(");");
                    builder.AppendLine("}");
                    break;
                case VividPerObjectPropertyType.Matrix:
                    builder.Append("float4x4 ").Append(accessorName).AppendLine("()");
                    builder.AppendLine("{");
                    builder.Append("    return VividPerObjectLoadFloat4x4(").Append(contextName).Append(", ")
                        .Append(offset).Append(", ").Append(FormatMatrix(definition.MatrixDefault)).AppendLine(");");
                    builder.AppendLine("}");
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
            builder.AppendLine();
        }

        private static string GetAccessorName(string uniqueName, string propertyName)
        {
            return $"VividPerObject_{uniqueName}_Access_{propertyName}";
        }

        private static string FormatInt(int value)
        {
            return $"asint(0x{unchecked((uint)value):X8}u)";
        }

        private static string FormatFloat(float value)
        {
            return $"asfloat(0x{unchecked((uint)BitConverter.SingleToInt32Bits(value)):X8}u)";
        }

        private static string FormatVector(Vector4 value)
        {
            return $"float4({FormatFloat(value.x)}, {FormatFloat(value.y)}, {FormatFloat(value.z)}, {FormatFloat(value.w)})";
        }

        private static string FormatMatrix(Matrix4x4 value)
        {
            var builder = new StringBuilder(512);
            builder.Append("float4x4(");
            for (int row = 0; row < 4; row++)
            {
                if (row > 0)
                    builder.Append(", ");
                builder.Append("float4(");
                for (int column = 0; column < 4; column++)
                {
                    if (column > 0)
                        builder.Append(", ");
                    builder.Append(FormatFloat(value[row, column]));
                }
                builder.Append(')');
            }
            builder.Append(')');
            return builder.ToString();
        }

        private static bool IsOwnedGeneratedFile(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath) || !File.Exists(assetPath))
                return false;

            using var reader = new StreamReader(assetPath);
            return string.Equals(reader.ReadLine(), GeneratedHeader, StringComparison.Ordinal);
        }
    }

    [InitializeOnLoad]
    internal static class VividPerObjectLayoutGenerationBootstrap
    {
        static VividPerObjectLayoutGenerationBootstrap()
        {
            EditorApplication.delayCall += VividPerObjectLayoutGenerator.GenerateAll;
        }
    }

    internal sealed class VividPerObjectLayoutPostprocessor : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            for (int i = 0; i < deletedAssets.Length; i++)
                VividPerObjectLayoutGenerator.DeleteGeneratedForDeletedLayout(deletedAssets[i]);

            for (int i = 0; i < importedAssets.Length; i++)
                GenerateIfLayout(importedAssets[i]);
            for (int i = 0; i < movedAssets.Length; i++)
                GenerateIfLayout(movedAssets[i]);
        }

        private static void GenerateIfLayout(string assetPath)
        {
            VividPerObjectLayout layout = AssetDatabase.LoadAssetAtPath<VividPerObjectLayout>(assetPath);
            if (layout != null)
                VividPerObjectLayoutGenerator.Generate(layout);
        }
    }

    internal sealed class VividPerObjectLayoutBuildPreprocessor : IPreprocessBuildWithReport
    {
        public int callbackOrder => 0;

        public void OnPreprocessBuild(BuildReport report)
        {
            try
            {
                VividPerObjectLayoutGenerator.GenerateAll();
            }
            catch (Exception exception)
            {
                throw new BuildFailedException($"Failed to generate Vivid per-object layout HLSL: {exception.Message}");
            }
        }
    }

    [CustomEditor(typeof(VividPerObjectLayout))]
    internal sealed class VividPerObjectLayoutEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            bool changed = DrawDefaultInspector();
            var layout = (VividPerObjectLayout)target;
            if (changed && AssetDatabase.Contains(layout))
                GenerateWithErrorDisplay(layout);

            EditorGUILayout.Space();
            bool synchronized = VividPerObjectLayoutGenerator.IsSynchronized(layout);
            EditorGUILayout.HelpBox(
                synchronized
                    ? $"Generated include: {layout.GeneratedIncludePath}"
                    : "Generated HLSL is missing or out of date.",
                synchronized ? MessageType.Info : MessageType.Warning);
            if (GUILayout.Button("Regenerate HLSL"))
                GenerateWithErrorDisplay(layout);
        }

        private static void GenerateWithErrorDisplay(VividPerObjectLayout layout)
        {
            try
            {
                VividPerObjectLayoutGenerator.Generate(layout);
            }
            catch (Exception exception)
            {
                Debug.LogException(exception, layout);
            }
        }
    }
}
