// <auto-generated by MaterialSurfaceHlslGenerator>
// Generated from canonical Surface Stage LIR; do not edit.
#ifndef VIVID_MATERIAL_SURFACE_AOT_GENERATED_INCLUDED
#define VIVID_MATERIAL_SURFACE_AOT_GENERATED_INCLUDED

#define VIVID_MATERIAL_SURFACE_HLSL_BACKEND_VERSION 2u

struct VividAOTSurfaceContext
{
    float2 UV0;
    float2 UV0Ddx;
    float2 UV0Ddy;
    float3 GeometryNormalWS;
    float4 GeometryTangentWS;
    float4 PositionCS;
};

struct VividAOTSurfaceSlabValues
{
    float4 BaseColor;
    float PerceptualRoughness;
    float Metallic;
    float3 NormalWS;
    float4 TangentWS;
    float3 NormalTS;
    float AmbientOcclusion;
    uint HasNormal;
    uint FeatureMask;
};

struct VividAOTSurfaceProgramOutput
{
    VividAOTSurfaceSlabValues BaseSlab;
    VividAOTSurfaceSlabValues TopSlab;
    float3 Emission;
    float LayerWeight;
    uint ClosureCount;
    uint LayerOperator;
};

// Surface AOT HLSL artifact v2, backend v2.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_StandardSingleSlab(
    const VividMaterialData materialParameters,
    const VividSurfaceBindingData surfaceBinding0,
    const VividAOTSurfaceContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float3 vivid_v0001 = context.GeometryNormalWS;
    const float4 vivid_v0002 = context.GeometryTangentWS;
    const float vivid_v0003 = materialParameters.Metallic;
    const float vivid_v0004 = materialParameters.Roughness;
    const float3 vivid_v0005 = materialParameters.Emission.xyz;
    const float4 vivid_v0006 = materialParameters.AlbedoColor;
    const float2 vivid_v0008 = context.UV0Ddx;
    const float2 vivid_v0009 = context.UV0Ddy;
    const VividSlabMaterialData vivid_sample_slab_10 = VividCreateSlabMaterialData(materialParameters);
    const float2 vivid_sample_uv_10 = vivid_v0000 * vivid_sample_slab_10.TextureTilingOffset.xy + vivid_sample_slab_10.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_10 = vivid_v0008 * vivid_sample_slab_10.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_10 = vivid_v0009 * vivid_sample_slab_10.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_10 = VividCreateSurfaceSampleContextGrad(surfaceBinding0, vivid_sample_uv_10, vivid_sample_ddx_10, vivid_sample_ddy_10, context.PositionCS);
    const float4 vivid_v0010 = VividSampleBaseColorGrad(surfaceBinding0, vivid_sample_context_10);
    const float4 vivid_v0011 = (vivid_v0006 * vivid_v0010);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0011;
    output.BaseSlab.PerceptualRoughness = vivid_v0004;
    output.BaseSlab.Metallic = vivid_v0003;
    output.BaseSlab.NormalWS = vivid_v0001;
    output.BaseSlab.TangentWS = vivid_v0002;
    output.BaseSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_base_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_10,
        surfaceBinding0,
        vivid_sample_context_10,
        true,
        true,
        output.BaseSlab.BaseColor.rgb,
        output.BaseSlab.PerceptualRoughness,
        output.BaseSlab.Metallic);
    output.BaseSlab.PerceptualRoughness = vivid_base_slab_detail.PerceptualRoughness;
    output.BaseSlab.Metallic = vivid_base_slab_detail.Metallic;
    output.BaseSlab.NormalTS = vivid_base_slab_detail.NormalTS;
    output.BaseSlab.AmbientOcclusion = vivid_base_slab_detail.AmbientOcclusion;
    output.BaseSlab.HasNormal = vivid_base_slab_detail.HasNormal;
    output.ClosureCount = 1u;
    output.LayerOperator = 0u;
    output.Emission = vivid_v0005;
    return output;
}

// Surface AOT HLSL artifact v2, backend v2.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_DualSlabHorizontalMix(
    const VividDualSlabMaterialData materialParameters,
    const VividSurfaceBindingData surfaceBinding0,
    const VividSurfaceBindingData surfaceBinding1,
    const VividAOTSurfaceContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float3 vivid_v0001 = context.GeometryNormalWS;
    const float4 vivid_v0002 = context.GeometryTangentWS;
    const float vivid_v0003 = materialParameters.LayerWeight;
    const float vivid_v0004 = materialParameters.BaseMetallic;
    const float vivid_v0005 = materialParameters.BaseRoughness;
    const float vivid_v0006 = materialParameters.TopMetallic;
    const float vivid_v0007 = materialParameters.TopRoughness;
    const float3 vivid_v0008 = materialParameters.Emission.xyz;
    const float4 vivid_v0009 = materialParameters.BaseAlbedoColor;
    const float4 vivid_v0010 = materialParameters.TopAlbedoColor;
    const float2 vivid_v0013 = context.UV0Ddx;
    const float2 vivid_v0014 = context.UV0Ddy;
    const VividSlabMaterialData vivid_sample_slab_15 = VividGetBaseSlabMaterialData(materialParameters);
    const float2 vivid_sample_uv_15 = vivid_v0000 * vivid_sample_slab_15.TextureTilingOffset.xy + vivid_sample_slab_15.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_15 = vivid_v0013 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_15 = vivid_v0014 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_15 = VividCreateSurfaceSampleContextGrad(surfaceBinding0, vivid_sample_uv_15, vivid_sample_ddx_15, vivid_sample_ddy_15, context.PositionCS);
    const float4 vivid_v0015 = VividSampleBaseColorGrad(surfaceBinding0, vivid_sample_context_15);
    const VividSlabMaterialData vivid_sample_slab_16 = VividGetTopSlabMaterialData(materialParameters);
    const float2 vivid_sample_uv_16 = vivid_v0000 * vivid_sample_slab_16.TextureTilingOffset.xy + vivid_sample_slab_16.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_16 = vivid_v0013 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_16 = vivid_v0014 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_16 = VividCreateSurfaceSampleContextGrad(surfaceBinding1, vivid_sample_uv_16, vivid_sample_ddx_16, vivid_sample_ddy_16, context.PositionCS);
    const float4 vivid_v0016 = VividSampleBaseColorGrad(surfaceBinding1, vivid_sample_context_16);
    const float4 vivid_v0017 = (vivid_v0009 * vivid_v0015);
    const float4 vivid_v0018 = (vivid_v0010 * vivid_v0016);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0017;
    output.BaseSlab.PerceptualRoughness = vivid_v0005;
    output.BaseSlab.Metallic = vivid_v0004;
    output.BaseSlab.NormalWS = vivid_v0001;
    output.BaseSlab.TangentWS = vivid_v0002;
    output.BaseSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_base_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_15,
        surfaceBinding0,
        vivid_sample_context_15,
        true,
        true,
        output.BaseSlab.BaseColor.rgb,
        output.BaseSlab.PerceptualRoughness,
        output.BaseSlab.Metallic);
    output.BaseSlab.PerceptualRoughness = vivid_base_slab_detail.PerceptualRoughness;
    output.BaseSlab.Metallic = vivid_base_slab_detail.Metallic;
    output.BaseSlab.NormalTS = vivid_base_slab_detail.NormalTS;
    output.BaseSlab.AmbientOcclusion = vivid_base_slab_detail.AmbientOcclusion;
    output.BaseSlab.HasNormal = vivid_base_slab_detail.HasNormal;
    output.TopSlab.BaseColor = vivid_v0018;
    output.TopSlab.PerceptualRoughness = vivid_v0007;
    output.TopSlab.Metallic = vivid_v0006;
    output.TopSlab.NormalWS = vivid_v0001;
    output.TopSlab.TangentWS = vivid_v0002;
    output.TopSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_top_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_16,
        surfaceBinding1,
        vivid_sample_context_16,
        true,
        true,
        output.TopSlab.BaseColor.rgb,
        output.TopSlab.PerceptualRoughness,
        output.TopSlab.Metallic);
    output.TopSlab.PerceptualRoughness = vivid_top_slab_detail.PerceptualRoughness;
    output.TopSlab.Metallic = vivid_top_slab_detail.Metallic;
    output.TopSlab.NormalTS = vivid_top_slab_detail.NormalTS;
    output.TopSlab.AmbientOcclusion = vivid_top_slab_detail.AmbientOcclusion;
    output.TopSlab.HasNormal = vivid_top_slab_detail.HasNormal;
    output.LayerWeight = vivid_v0003;
    output.ClosureCount = 2u;
    output.LayerOperator = 1u;
    output.Emission = vivid_v0008;
    return output;
}

// Surface AOT HLSL artifact v2, backend v2.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_DualSlabVerticalLayer(
    const VividDualSlabMaterialData materialParameters,
    const VividSurfaceBindingData surfaceBinding0,
    const VividSurfaceBindingData surfaceBinding1,
    const VividAOTSurfaceContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float3 vivid_v0001 = context.GeometryNormalWS;
    const float4 vivid_v0002 = context.GeometryTangentWS;
    const float vivid_v0003 = materialParameters.LayerWeight;
    const float vivid_v0004 = materialParameters.BaseMetallic;
    const float vivid_v0005 = materialParameters.BaseRoughness;
    const float vivid_v0006 = materialParameters.TopMetallic;
    const float vivid_v0007 = materialParameters.TopRoughness;
    const float3 vivid_v0008 = materialParameters.Emission.xyz;
    const float4 vivid_v0009 = materialParameters.BaseAlbedoColor;
    const float4 vivid_v0010 = materialParameters.TopAlbedoColor;
    const float2 vivid_v0013 = context.UV0Ddx;
    const float2 vivid_v0014 = context.UV0Ddy;
    const VividSlabMaterialData vivid_sample_slab_15 = VividGetBaseSlabMaterialData(materialParameters);
    const float2 vivid_sample_uv_15 = vivid_v0000 * vivid_sample_slab_15.TextureTilingOffset.xy + vivid_sample_slab_15.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_15 = vivid_v0013 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_15 = vivid_v0014 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_15 = VividCreateSurfaceSampleContextGrad(surfaceBinding0, vivid_sample_uv_15, vivid_sample_ddx_15, vivid_sample_ddy_15, context.PositionCS);
    const float4 vivid_v0015 = VividSampleBaseColorGrad(surfaceBinding0, vivid_sample_context_15);
    const VividSlabMaterialData vivid_sample_slab_16 = VividGetTopSlabMaterialData(materialParameters);
    const float2 vivid_sample_uv_16 = vivid_v0000 * vivid_sample_slab_16.TextureTilingOffset.xy + vivid_sample_slab_16.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_16 = vivid_v0013 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_16 = vivid_v0014 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_16 = VividCreateSurfaceSampleContextGrad(surfaceBinding1, vivid_sample_uv_16, vivid_sample_ddx_16, vivid_sample_ddy_16, context.PositionCS);
    const float4 vivid_v0016 = VividSampleBaseColorGrad(surfaceBinding1, vivid_sample_context_16);
    const float4 vivid_v0017 = (vivid_v0009 * vivid_v0015);
    const float4 vivid_v0018 = (vivid_v0010 * vivid_v0016);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0017;
    output.BaseSlab.PerceptualRoughness = vivid_v0005;
    output.BaseSlab.Metallic = vivid_v0004;
    output.BaseSlab.NormalWS = vivid_v0001;
    output.BaseSlab.TangentWS = vivid_v0002;
    output.BaseSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_base_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_15,
        surfaceBinding0,
        vivid_sample_context_15,
        true,
        true,
        output.BaseSlab.BaseColor.rgb,
        output.BaseSlab.PerceptualRoughness,
        output.BaseSlab.Metallic);
    output.BaseSlab.PerceptualRoughness = vivid_base_slab_detail.PerceptualRoughness;
    output.BaseSlab.Metallic = vivid_base_slab_detail.Metallic;
    output.BaseSlab.NormalTS = vivid_base_slab_detail.NormalTS;
    output.BaseSlab.AmbientOcclusion = vivid_base_slab_detail.AmbientOcclusion;
    output.BaseSlab.HasNormal = vivid_base_slab_detail.HasNormal;
    output.TopSlab.BaseColor = vivid_v0018;
    output.TopSlab.PerceptualRoughness = vivid_v0007;
    output.TopSlab.Metallic = vivid_v0006;
    output.TopSlab.NormalWS = vivid_v0001;
    output.TopSlab.TangentWS = vivid_v0002;
    output.TopSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_top_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_16,
        surfaceBinding1,
        vivid_sample_context_16,
        true,
        true,
        output.TopSlab.BaseColor.rgb,
        output.TopSlab.PerceptualRoughness,
        output.TopSlab.Metallic);
    output.TopSlab.PerceptualRoughness = vivid_top_slab_detail.PerceptualRoughness;
    output.TopSlab.Metallic = vivid_top_slab_detail.Metallic;
    output.TopSlab.NormalTS = vivid_top_slab_detail.NormalTS;
    output.TopSlab.AmbientOcclusion = vivid_top_slab_detail.AmbientOcclusion;
    output.TopSlab.HasNormal = vivid_top_slab_detail.HasNormal;
    output.LayerWeight = vivid_v0003;
    output.ClosureCount = 2u;
    output.LayerOperator = 2u;
    output.Emission = vivid_v0008;
    return output;
}

bool VividTryEvaluateAOTSurfaceProgram(
    const uint programID,
    const VividMaterialData materialParameters,
    const VividDualSlabMaterialData dualSlabMaterialParameters,
    const VividSurfaceBindingData surfaceBinding0,
    const VividSurfaceBindingData surfaceBinding1,
    const VividAOTSurfaceContext context,
    out VividAOTSurfaceProgramOutput output)
{
    output = (VividAOTSurfaceProgramOutput) 0;
    switch (programID)
    {
        case 0u:
            output = VividEvaluateAOTSurface_StandardSingleSlab(
                materialParameters,
                surfaceBinding0,
                context);
            return true;
        case 1u:
            output = VividEvaluateAOTSurface_DualSlabHorizontalMix(
                dualSlabMaterialParameters,
                surfaceBinding0,
                surfaceBinding1,
                context);
            return true;
        case 2u:
            output = VividEvaluateAOTSurface_DualSlabVerticalLayer(
                dualSlabMaterialParameters,
                surfaceBinding0,
                surfaceBinding1,
                context);
            return true;
        default:
            return false;
    }
}

#endif // VIVID_MATERIAL_SURFACE_AOT_GENERATED_INCLUDED
