// <auto-generated by MaterialSurfaceHlslGenerator>
// Generated from canonical Surface Stage LIR and Deferred Export contracts; do not edit.
#ifndef VIVID_MATERIAL_SURFACE_AOT_GENERATED_INCLUDED
#define VIVID_MATERIAL_SURFACE_AOT_GENERATED_INCLUDED
#include "../VividOpenPBROpaqueContract.hlsl"

#define VIVID_MATERIAL_SURFACE_HLSL_BACKEND_VERSION 9u

// Expected Material Program artifact set: v2 0xDBFA1A8CE789E0DE
#include "VividMaterialProgramCatalogStamp.generated.hlsl"
#if !defined(VIVID_MATERIAL_PUBLISHED_ARTIFACT_SET_INCLUDED)
#error Missing published Material Program Catalog stamp for Surface dispatcher.
#elif !defined(VIVID_MATERIAL_PUBLISHED_ARTIFACT_SET_V00000002_HDBFA1A8CE789E0DE)
#error Surface dispatcher does not match the published Material Program Catalog artifact set.
#endif

#ifndef VIVID_MATERIAL_CATALOG_MANIFEST_INCLUDED
#define VIVID_MATERIAL_CATALOG_MANIFEST_INCLUDED
#define VIVID_MATERIAL_CATALOG_MANIFEST_V00000006_HE73E4F7E34E02EF3_N00000005 1
#elif !defined(VIVID_MATERIAL_CATALOG_MANIFEST_V00000006_HE73E4F7E34E02EF3_N00000005)
#error Material dispatchers use different frozen catalog manifests.
#endif

#define VIVID_AOT_DEFERRED_EXPORT_CONTRACT_VERSION 2u
#define VIVID_AOT_DEFERRED_EXPORT_SURFACE_SUMMARY_ABI_NONE 0u
#define VIVID_AOT_DEFERRED_EXPORT_SURFACE_SUMMARY_ABI_V1 1u
#define VIVID_AOT_DEFERRED_EXPORT_NATIVE_PAYLOAD_ABI_NONE 0u
#define VIVID_AOT_DEFERRED_EXPORT_NATIVE_PAYLOAD_ABI_OPENPBR_OPAQUE_V1 1u
#define VIVID_AOT_DEFERRED_EXPORT_SIDECAR_ABI_NONE 0u
#define VIVID_AOT_DEFERRED_EXPORT_SIDECAR_ABI_DUAL_SLAB_V1 1u
#define VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_STANDARD_LIT 1u
#define VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_UNLIT 2u
#define VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_OPENPBR_OPAQUE 4u
#define VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_NONE 0u
#define VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_FAST_SLAB 2u
#define VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_DUAL_SLAB 4u
#define VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_OPENPBR_OPAQUE 6u
#define VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_NONE 0u
#define VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_HORIZONTAL_MIX 1u
#define VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_VERTICAL_LAYER 2u
#define VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_SURFACE_SUMMARY 1u
#define VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_DIFFUSE_IRRADIANCE 2u
#define VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_DUAL_SLAB_SIDECAR 4u
#define VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_SHARED_NORMAL_AO 8u
#define VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_NATIVE_OPENPBR_OPAQUE 16u
#define VIVID_AOT_DEFERRED_EXPORT_POLICY_DYNAMIC_DIFFUSE_IRRADIANCE 1u
#define VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_SSR_ON_FAST_SLAB 2u
#define VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_DECALS 4u
#define VIVID_AOT_DEFERRED_EXPORT_POLICY_FAST_SLAB_WHEN_SIDECAR_EMPTY 8u

struct VividAOTDeferredExportContract
{
    uint Version;
    uint SurfaceSummaryAbi;
    uint DualSlabSidecarAbi;
    uint NativePayloadAbi;
    uint NativeProfileVersion;
    uint NativeProfileFingerprintLo;
    uint NativeProfileFingerprintHi;
    uint ShadingModelMask;
    uint LitClass;
    uint ExpectedClosureCount;
    uint Topology;
    uint PayloadFlags;
    uint PolicyFlags;
};

bool VividAOTDeferredExportHasShadingModel(
    const VividAOTDeferredExportContract contract,
    const uint shadingModel)
{
    return (contract.ShadingModelMask & shadingModel) == shadingModel;
}

bool VividAOTDeferredExportHasPayload(
    const VividAOTDeferredExportContract contract,
    const uint payload)
{
    return (contract.PayloadFlags & payload) == payload;
}

bool VividAOTDeferredExportHasPolicy(
    const VividAOTDeferredExportContract contract,
    const uint policy)
{
    return (contract.PolicyFlags & policy) == policy;
}

bool VividIsAOTDeferredExportContractSupported(
    const VividAOTDeferredExportContract contract)
{
    if (contract.Version != VIVID_AOT_DEFERRED_EXPORT_CONTRACT_VERSION)
        return false;
    if (contract.NativePayloadAbi == VIVID_AOT_DEFERRED_EXPORT_NATIVE_PAYLOAD_ABI_OPENPBR_OPAQUE_V1)
    {
        return contract.SurfaceSummaryAbi == VIVID_AOT_DEFERRED_EXPORT_SURFACE_SUMMARY_ABI_NONE
            && contract.DualSlabSidecarAbi == VIVID_AOT_DEFERRED_EXPORT_SIDECAR_ABI_NONE
            && contract.NativeProfileVersion == VIVID_OPENPBR_OPAQUE_CONTRACT_VERSION
            && contract.NativeProfileFingerprintLo == VIVID_OPENPBR_OPAQUE_FINGERPRINT_LO
            && contract.NativeProfileFingerprintHi == VIVID_OPENPBR_OPAQUE_FINGERPRINT_HI
            && contract.ShadingModelMask == VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_OPENPBR_OPAQUE
            && contract.LitClass == VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_OPENPBR_OPAQUE
            && contract.ExpectedClosureCount == VIVID_OPENPBR_OPAQUE_CLOSURE_COUNT
            && contract.Topology == VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_NONE
            && contract.PayloadFlags == VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_NATIVE_OPENPBR_OPAQUE
            && contract.PolicyFlags == 0u;
    }
    if (contract.NativePayloadAbi != VIVID_AOT_DEFERRED_EXPORT_NATIVE_PAYLOAD_ABI_NONE
        || contract.NativeProfileVersion != 0u
        || contract.NativeProfileFingerprintLo != 0u
        || contract.NativeProfileFingerprintHi != 0u
        || contract.SurfaceSummaryAbi != VIVID_AOT_DEFERRED_EXPORT_SURFACE_SUMMARY_ABI_V1)
        return false;

    const uint knownShadingModels =
        VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_STANDARD_LIT
        | VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_UNLIT;
    if (contract.ShadingModelMask == 0u
        || (contract.ShadingModelMask & ~knownShadingModels) != 0u)
        return false;

    const bool isSingle = contract.Topology
        == VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_NONE;
    const bool isDual = contract.Topology
            == VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_HORIZONTAL_MIX
        || contract.Topology
            == VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_VERTICAL_LAYER;
    if ((!isSingle && !isDual)
        || contract.ExpectedClosureCount != (isDual ? 2u : 1u))
        return false;

    const uint corePayload =
        VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_SURFACE_SUMMARY
        | VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_DIFFUSE_IRRADIANCE;
    const uint knownPayload = corePayload
        | VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_DUAL_SLAB_SIDECAR
        | VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_SHARED_NORMAL_AO;
    if ((contract.PayloadFlags & corePayload) != corePayload
        || (contract.PayloadFlags & ~knownPayload) != 0u)
        return false;

    const uint knownPolicy =
        VIVID_AOT_DEFERRED_EXPORT_POLICY_DYNAMIC_DIFFUSE_IRRADIANCE
        | VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_SSR_ON_FAST_SLAB
        | VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_DECALS
        | VIVID_AOT_DEFERRED_EXPORT_POLICY_FAST_SLAB_WHEN_SIDECAR_EMPTY;
    if ((contract.PolicyFlags & ~knownPolicy) != 0u
        || !VividAOTDeferredExportHasPolicy(
            contract,
            VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_DECALS))
        return false;

    const bool supportsLit = VividAOTDeferredExportHasShadingModel(
        contract,
        VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_STANDARD_LIT);
    const uint expectedLitClass = !supportsLit
        ? VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_NONE
        : isDual
            ? VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_DUAL_SLAB
            : VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_FAST_SLAB;
    if (contract.LitClass != expectedLitClass)
        return false;

    const bool expectsDualSidecar = supportsLit && isDual;
    const bool hasDualSidecar = VividAOTDeferredExportHasPayload(
        contract,
        VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_DUAL_SLAB_SIDECAR);
    const bool sharesNormalAO = VividAOTDeferredExportHasPayload(
        contract,
        VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_SHARED_NORMAL_AO);
    const bool hasDualSidecarAbi = contract.DualSlabSidecarAbi
        == VIVID_AOT_DEFERRED_EXPORT_SIDECAR_ABI_DUAL_SLAB_V1;
    if ((contract.DualSlabSidecarAbi
            != VIVID_AOT_DEFERRED_EXPORT_SIDECAR_ABI_NONE
            && !hasDualSidecarAbi)
        || hasDualSidecar != expectsDualSidecar
        || sharesNormalAO != isDual
        || hasDualSidecarAbi != expectsDualSidecar)
        return false;

    const uint litPolicies =
        VIVID_AOT_DEFERRED_EXPORT_POLICY_DYNAMIC_DIFFUSE_IRRADIANCE
        | VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_SSR_ON_FAST_SLAB;
    const uint activeLitPolicies = contract.PolicyFlags & litPolicies;
    const bool hasFastFallback = VividAOTDeferredExportHasPolicy(
        contract,
        VIVID_AOT_DEFERRED_EXPORT_POLICY_FAST_SLAB_WHEN_SIDECAR_EMPTY);
    return activeLitPolicies == (supportsLit ? litPolicies : 0u)
        && hasFastFallback == expectsDualSidecar;
}

struct VividAOTSurfaceContext
{
    float2 UV0;
    float2 UV0Ddx;
    float2 UV0Ddy;
    float3 GeometryNormalWS;
    float4 GeometryTangentWS;
    float4 PositionCS;
};

struct VividAOTSurfaceSlabValues
{
    float4 BaseColor;
    float PerceptualRoughness;
    float Metallic;
    float3 NormalWS;
    float4 TangentWS;
    float3 NormalTS;
    float AmbientOcclusion;
    uint HasNormal;
    uint FeatureMask;
};

struct VividAOTSurfaceProgramOutput
{
    uint Profile;
    uint NativeProfileVersion;
    uint NativeProfileFingerprintLo;
    uint NativeProfileFingerprintHi;
    VividOpenPBROpaqueInputs OpenPBROpaque;
    VividAOTSurfaceSlabValues BaseSlab;
    VividAOTSurfaceSlabValues TopSlab;
    float3 Emission;
    float LayerWeight;
    uint ClosureCount;
    uint LayerOperator;
};

#define VIVID_AOT_SURFACE_PROFILE_SLAB 0u
#define VIVID_AOT_SURFACE_PROFILE_OPENPBR_OPAQUE 1u
// Surface AOT HLSL artifact v5, backend v9.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_215C5B2731CAFB52(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTSurfaceContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float3 vivid_v0001 = context.GeometryNormalWS;
    const float4 vivid_v0002 = context.GeometryTangentWS;
    const float vivid_v0003 = VividLoadMaterialFloat(parameterAddress, 11u);
    const float vivid_v0004 = VividLoadMaterialFloat(parameterAddress, 12u);
    const float3 vivid_v0005 = VividLoadMaterialFloat3(parameterAddress, 8u);
    const float4 vivid_v0006 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float2 vivid_v0008 = context.UV0Ddx;
    const float2 vivid_v0009 = context.UV0Ddy;
    const VividMaterialResourceData vivid_sample_resource_10 = PullMaterialResourceData(resourceAddress + 0u);
    VividSurfaceBindingData vivid_sample_binding_10;
    vivid_sample_binding_10.BaseColorResource = vivid_sample_resource_10.BaseColorResource;
    vivid_sample_binding_10.NormalResource = vivid_sample_resource_10.NormalResource;
    vivid_sample_binding_10.MaskResource = vivid_sample_resource_10.MaskResource;
    vivid_sample_binding_10.Flags = vivid_sample_resource_10.SurfaceBindingFlags;
    vivid_sample_binding_10.UVScaleBias = vivid_sample_resource_10.UVScaleBias;
    const VividSlabMaterialData vivid_sample_slab_10 = VividCreateSlabMaterialData(vivid_sample_resource_10);
    const float2 vivid_sample_uv_10 = vivid_v0000 * vivid_sample_slab_10.TextureTilingOffset.xy + vivid_sample_slab_10.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_10 = vivid_v0008 * vivid_sample_slab_10.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_10 = vivid_v0009 * vivid_sample_slab_10.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_10 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_10, vivid_sample_uv_10, vivid_sample_ddx_10, vivid_sample_ddy_10, context.PositionCS);
    const float4 vivid_v0010 = VividSampleBaseColorGrad(vivid_sample_binding_10, vivid_sample_context_10);
    const float4 vivid_v0011 = (vivid_v0006 * vivid_v0010);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0011;
    output.BaseSlab.PerceptualRoughness = vivid_v0004;
    output.BaseSlab.Metallic = vivid_v0003;
    output.BaseSlab.NormalWS = vivid_v0001;
    output.BaseSlab.TangentWS = vivid_v0002;
    output.BaseSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_base_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_10,
        vivid_sample_binding_10,
        vivid_sample_context_10,
        true,
        true,
        output.BaseSlab.BaseColor.rgb,
        output.BaseSlab.PerceptualRoughness,
        output.BaseSlab.Metallic);
    output.BaseSlab.PerceptualRoughness = vivid_base_slab_detail.PerceptualRoughness;
    output.BaseSlab.Metallic = vivid_base_slab_detail.Metallic;
    output.BaseSlab.NormalTS = vivid_base_slab_detail.NormalTS;
    output.BaseSlab.AmbientOcclusion = vivid_base_slab_detail.AmbientOcclusion;
    output.BaseSlab.HasNormal = vivid_base_slab_detail.HasNormal;
    output.ClosureCount = 1u;
    output.LayerOperator = 0u;
    output.Emission = vivid_v0005;
    return output;
}

// Surface AOT HLSL artifact v5, backend v9.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_130EA2D589CBAD8C(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTSurfaceContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float3 vivid_v0001 = context.GeometryNormalWS;
    const float4 vivid_v0002 = context.GeometryTangentWS;
    const float vivid_v0003 = VividLoadMaterialFloat(parameterAddress, 11u);
    const float vivid_v0004 = VividLoadMaterialFloat(parameterAddress, 12u);
    const float vivid_v0005 = VividLoadMaterialFloat(parameterAddress, 13u);
    const float vivid_v0006 = VividLoadMaterialFloat(parameterAddress, 20u);
    const float vivid_v0007 = VividLoadMaterialFloat(parameterAddress, 21u);
    const float3 vivid_v0008 = VividLoadMaterialFloat3(parameterAddress, 8u);
    const float4 vivid_v0009 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float4 vivid_v0010 = VividLoadMaterialFloat4(parameterAddress, 16u);
    const float2 vivid_v0013 = context.UV0Ddx;
    const float2 vivid_v0014 = context.UV0Ddy;
    const VividMaterialResourceData vivid_sample_resource_15 = PullMaterialResourceData(resourceAddress + 0u);
    VividSurfaceBindingData vivid_sample_binding_15;
    vivid_sample_binding_15.BaseColorResource = vivid_sample_resource_15.BaseColorResource;
    vivid_sample_binding_15.NormalResource = vivid_sample_resource_15.NormalResource;
    vivid_sample_binding_15.MaskResource = vivid_sample_resource_15.MaskResource;
    vivid_sample_binding_15.Flags = vivid_sample_resource_15.SurfaceBindingFlags;
    vivid_sample_binding_15.UVScaleBias = vivid_sample_resource_15.UVScaleBias;
    const VividSlabMaterialData vivid_sample_slab_15 = VividCreateSlabMaterialData(vivid_sample_resource_15);
    const float2 vivid_sample_uv_15 = vivid_v0000 * vivid_sample_slab_15.TextureTilingOffset.xy + vivid_sample_slab_15.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_15 = vivid_v0013 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_15 = vivid_v0014 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_15 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_15, vivid_sample_uv_15, vivid_sample_ddx_15, vivid_sample_ddy_15, context.PositionCS);
    const float4 vivid_v0015 = VividSampleBaseColorGrad(vivid_sample_binding_15, vivid_sample_context_15);
    const VividMaterialResourceData vivid_sample_resource_16 = PullMaterialResourceData(resourceAddress + 1u);
    VividSurfaceBindingData vivid_sample_binding_16;
    vivid_sample_binding_16.BaseColorResource = vivid_sample_resource_16.BaseColorResource;
    vivid_sample_binding_16.NormalResource = vivid_sample_resource_16.NormalResource;
    vivid_sample_binding_16.MaskResource = vivid_sample_resource_16.MaskResource;
    vivid_sample_binding_16.Flags = vivid_sample_resource_16.SurfaceBindingFlags;
    vivid_sample_binding_16.UVScaleBias = vivid_sample_resource_16.UVScaleBias;
    const VividSlabMaterialData vivid_sample_slab_16 = VividCreateSlabMaterialData(vivid_sample_resource_16);
    const float2 vivid_sample_uv_16 = vivid_v0000 * vivid_sample_slab_16.TextureTilingOffset.xy + vivid_sample_slab_16.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_16 = vivid_v0013 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_16 = vivid_v0014 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_16 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_16, vivid_sample_uv_16, vivid_sample_ddx_16, vivid_sample_ddy_16, context.PositionCS);
    const float4 vivid_v0016 = VividSampleBaseColorGrad(vivid_sample_binding_16, vivid_sample_context_16);
    const float4 vivid_v0017 = (vivid_v0009 * vivid_v0015);
    const float4 vivid_v0018 = (vivid_v0010 * vivid_v0016);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0017;
    output.BaseSlab.PerceptualRoughness = vivid_v0005;
    output.BaseSlab.Metallic = vivid_v0004;
    output.BaseSlab.NormalWS = vivid_v0001;
    output.BaseSlab.TangentWS = vivid_v0002;
    output.BaseSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_base_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_15,
        vivid_sample_binding_15,
        vivid_sample_context_15,
        true,
        true,
        output.BaseSlab.BaseColor.rgb,
        output.BaseSlab.PerceptualRoughness,
        output.BaseSlab.Metallic);
    output.BaseSlab.PerceptualRoughness = vivid_base_slab_detail.PerceptualRoughness;
    output.BaseSlab.Metallic = vivid_base_slab_detail.Metallic;
    output.BaseSlab.NormalTS = vivid_base_slab_detail.NormalTS;
    output.BaseSlab.AmbientOcclusion = vivid_base_slab_detail.AmbientOcclusion;
    output.BaseSlab.HasNormal = vivid_base_slab_detail.HasNormal;
    output.TopSlab.BaseColor = vivid_v0018;
    output.TopSlab.PerceptualRoughness = vivid_v0007;
    output.TopSlab.Metallic = vivid_v0006;
    output.TopSlab.NormalWS = vivid_v0001;
    output.TopSlab.TangentWS = vivid_v0002;
    output.TopSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_top_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_16,
        vivid_sample_binding_16,
        vivid_sample_context_16,
        true,
        true,
        output.TopSlab.BaseColor.rgb,
        output.TopSlab.PerceptualRoughness,
        output.TopSlab.Metallic);
    output.TopSlab.PerceptualRoughness = vivid_top_slab_detail.PerceptualRoughness;
    output.TopSlab.Metallic = vivid_top_slab_detail.Metallic;
    output.TopSlab.NormalTS = vivid_top_slab_detail.NormalTS;
    output.TopSlab.AmbientOcclusion = vivid_top_slab_detail.AmbientOcclusion;
    output.TopSlab.HasNormal = vivid_top_slab_detail.HasNormal;
    output.LayerWeight = vivid_v0003;
    output.ClosureCount = 2u;
    output.LayerOperator = 1u;
    output.Emission = vivid_v0008;
    return output;
}

// Surface AOT HLSL artifact v5, backend v9.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_527E00D079249214(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTSurfaceContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float3 vivid_v0001 = context.GeometryNormalWS;
    const float4 vivid_v0002 = context.GeometryTangentWS;
    const float vivid_v0003 = VividLoadMaterialFloat(parameterAddress, 11u);
    const float vivid_v0004 = VividLoadMaterialFloat(parameterAddress, 12u);
    const float vivid_v0005 = VividLoadMaterialFloat(parameterAddress, 13u);
    const float vivid_v0006 = VividLoadMaterialFloat(parameterAddress, 20u);
    const float vivid_v0007 = VividLoadMaterialFloat(parameterAddress, 21u);
    const float3 vivid_v0008 = VividLoadMaterialFloat3(parameterAddress, 8u);
    const float4 vivid_v0009 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float4 vivid_v0010 = VividLoadMaterialFloat4(parameterAddress, 16u);
    const float2 vivid_v0013 = context.UV0Ddx;
    const float2 vivid_v0014 = context.UV0Ddy;
    const VividMaterialResourceData vivid_sample_resource_15 = PullMaterialResourceData(resourceAddress + 0u);
    VividSurfaceBindingData vivid_sample_binding_15;
    vivid_sample_binding_15.BaseColorResource = vivid_sample_resource_15.BaseColorResource;
    vivid_sample_binding_15.NormalResource = vivid_sample_resource_15.NormalResource;
    vivid_sample_binding_15.MaskResource = vivid_sample_resource_15.MaskResource;
    vivid_sample_binding_15.Flags = vivid_sample_resource_15.SurfaceBindingFlags;
    vivid_sample_binding_15.UVScaleBias = vivid_sample_resource_15.UVScaleBias;
    const VividSlabMaterialData vivid_sample_slab_15 = VividCreateSlabMaterialData(vivid_sample_resource_15);
    const float2 vivid_sample_uv_15 = vivid_v0000 * vivid_sample_slab_15.TextureTilingOffset.xy + vivid_sample_slab_15.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_15 = vivid_v0013 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_15 = vivid_v0014 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_15 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_15, vivid_sample_uv_15, vivid_sample_ddx_15, vivid_sample_ddy_15, context.PositionCS);
    const float4 vivid_v0015 = VividSampleBaseColorGrad(vivid_sample_binding_15, vivid_sample_context_15);
    const VividMaterialResourceData vivid_sample_resource_16 = PullMaterialResourceData(resourceAddress + 1u);
    VividSurfaceBindingData vivid_sample_binding_16;
    vivid_sample_binding_16.BaseColorResource = vivid_sample_resource_16.BaseColorResource;
    vivid_sample_binding_16.NormalResource = vivid_sample_resource_16.NormalResource;
    vivid_sample_binding_16.MaskResource = vivid_sample_resource_16.MaskResource;
    vivid_sample_binding_16.Flags = vivid_sample_resource_16.SurfaceBindingFlags;
    vivid_sample_binding_16.UVScaleBias = vivid_sample_resource_16.UVScaleBias;
    const VividSlabMaterialData vivid_sample_slab_16 = VividCreateSlabMaterialData(vivid_sample_resource_16);
    const float2 vivid_sample_uv_16 = vivid_v0000 * vivid_sample_slab_16.TextureTilingOffset.xy + vivid_sample_slab_16.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_16 = vivid_v0013 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_16 = vivid_v0014 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_16 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_16, vivid_sample_uv_16, vivid_sample_ddx_16, vivid_sample_ddy_16, context.PositionCS);
    const float4 vivid_v0016 = VividSampleBaseColorGrad(vivid_sample_binding_16, vivid_sample_context_16);
    const float4 vivid_v0017 = (vivid_v0009 * vivid_v0015);
    const float4 vivid_v0018 = (vivid_v0010 * vivid_v0016);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0017;
    output.BaseSlab.PerceptualRoughness = vivid_v0005;
    output.BaseSlab.Metallic = vivid_v0004;
    output.BaseSlab.NormalWS = vivid_v0001;
    output.BaseSlab.TangentWS = vivid_v0002;
    output.BaseSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_base_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_15,
        vivid_sample_binding_15,
        vivid_sample_context_15,
        true,
        true,
        output.BaseSlab.BaseColor.rgb,
        output.BaseSlab.PerceptualRoughness,
        output.BaseSlab.Metallic);
    output.BaseSlab.PerceptualRoughness = vivid_base_slab_detail.PerceptualRoughness;
    output.BaseSlab.Metallic = vivid_base_slab_detail.Metallic;
    output.BaseSlab.NormalTS = vivid_base_slab_detail.NormalTS;
    output.BaseSlab.AmbientOcclusion = vivid_base_slab_detail.AmbientOcclusion;
    output.BaseSlab.HasNormal = vivid_base_slab_detail.HasNormal;
    output.TopSlab.BaseColor = vivid_v0018;
    output.TopSlab.PerceptualRoughness = vivid_v0007;
    output.TopSlab.Metallic = vivid_v0006;
    output.TopSlab.NormalWS = vivid_v0001;
    output.TopSlab.TangentWS = vivid_v0002;
    output.TopSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_top_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_16,
        vivid_sample_binding_16,
        vivid_sample_context_16,
        true,
        true,
        output.TopSlab.BaseColor.rgb,
        output.TopSlab.PerceptualRoughness,
        output.TopSlab.Metallic);
    output.TopSlab.PerceptualRoughness = vivid_top_slab_detail.PerceptualRoughness;
    output.TopSlab.Metallic = vivid_top_slab_detail.Metallic;
    output.TopSlab.NormalTS = vivid_top_slab_detail.NormalTS;
    output.TopSlab.AmbientOcclusion = vivid_top_slab_detail.AmbientOcclusion;
    output.TopSlab.HasNormal = vivid_top_slab_detail.HasNormal;
    output.LayerWeight = vivid_v0003;
    output.ClosureCount = 2u;
    output.LayerOperator = 2u;
    output.Emission = vivid_v0008;
    return output;
}

// Surface AOT HLSL artifact v5, backend v9.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_FCBA57D9E58B9CDC(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTSurfaceContext context)
{
    const float vivid_v0000 = asfloat(0x3F000000u);
    const float3 vivid_v0001 = float3(asfloat(0x3D4CCCCDu), asfloat(0x3DCCCCCDu), asfloat(0x3E19999Au));
    const float4 vivid_v0002 = float4(asfloat(0x3F000000u), asfloat(0x3E800000u), asfloat(0x3F400000u), asfloat(0x3F800000u));
    const float2 vivid_v0003 = context.UV0;
    const float3 vivid_v0004 = context.GeometryNormalWS;
    const float4 vivid_v0005 = context.GeometryTangentWS;
    const float vivid_v0006 = VividLoadMaterialFloat(parameterAddress, 11u);
    const float vivid_v0007 = VividLoadMaterialFloat(parameterAddress, 12u);
    const float3 vivid_v0008 = VividLoadMaterialFloat3(parameterAddress, 8u);
    const float4 vivid_v0009 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float2 vivid_v0011 = context.UV0Ddx;
    const float2 vivid_v0012 = context.UV0Ddy;
    const float3 vivid_v0013 = (vivid_v0001 + vivid_v0008);
    const float vivid_v0014 = (vivid_v0000 * vivid_v0006);
    const float vivid_v0015 = (1.0f - vivid_v0007);
    const VividMaterialResourceData vivid_sample_resource_16 = PullMaterialResourceData(resourceAddress + 0u);
    VividSurfaceBindingData vivid_sample_binding_16;
    vivid_sample_binding_16.BaseColorResource = vivid_sample_resource_16.BaseColorResource;
    vivid_sample_binding_16.NormalResource = vivid_sample_resource_16.NormalResource;
    vivid_sample_binding_16.MaskResource = vivid_sample_resource_16.MaskResource;
    vivid_sample_binding_16.Flags = vivid_sample_resource_16.SurfaceBindingFlags;
    vivid_sample_binding_16.UVScaleBias = vivid_sample_resource_16.UVScaleBias;
    const VividSlabMaterialData vivid_sample_slab_16 = VividCreateSlabMaterialData(vivid_sample_resource_16);
    const float2 vivid_sample_uv_16 = vivid_v0003 * vivid_sample_slab_16.TextureTilingOffset.xy + vivid_sample_slab_16.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_16 = vivid_v0011 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_16 = vivid_v0012 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_16 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_16, vivid_sample_uv_16, vivid_sample_ddx_16, vivid_sample_ddy_16, context.PositionCS);
    const float4 vivid_v0016 = VividSampleBaseColorGrad(vivid_sample_binding_16, vivid_sample_context_16);
    const float vivid_v0017 = saturate(vivid_v0014);
    const float4 vivid_v0018 = (vivid_v0009 * vivid_v0016);
    const float4 vivid_v0019 = (vivid_v0002 * vivid_v0018);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0019;
    output.BaseSlab.PerceptualRoughness = vivid_v0015;
    output.BaseSlab.Metallic = vivid_v0017;
    output.BaseSlab.NormalWS = vivid_v0004;
    output.BaseSlab.TangentWS = vivid_v0005;
    output.BaseSlab.FeatureMask = 1u;
    output.BaseSlab.NormalTS = float3(0.0f, 0.0f, 1.0f);
    output.BaseSlab.AmbientOcclusion = 1.0f;
    output.BaseSlab.HasNormal = false;
    output.ClosureCount = 1u;
    output.LayerOperator = 0u;
    output.Emission = vivid_v0013;
    return output;
}

// Surface AOT HLSL artifact v5, backend v9.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_30B108E514D38D6E(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTSurfaceContext context)
{
    const float vivid_v0000 = asfloat(0x00000000u);
    const float vivid_v0001 = asfloat(0x3E99999Au);
    const float vivid_v0002 = asfloat(0x3F800000u);
    const float vivid_v0003 = asfloat(0x40000000u);
    const float3 vivid_v0004 = float3(asfloat(0x3F4CCCCDu), asfloat(0x3F4CCCCDu), asfloat(0x3F4CCCCDu));
    const float3 vivid_v0005 = float3(asfloat(0x3F800000u), asfloat(0x3F800000u), asfloat(0x3F800000u));
    const float3 vivid_v0006 = context.GeometryNormalWS;

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.Profile = VIVID_AOT_SURFACE_PROFILE_OPENPBR_OPAQUE;
    output.NativeProfileVersion = VIVID_OPENPBR_OPAQUE_CONTRACT_VERSION;
    output.NativeProfileFingerprintLo = VIVID_OPENPBR_OPAQUE_FINGERPRINT_LO;
    output.NativeProfileFingerprintHi = VIVID_OPENPBR_OPAQUE_FINGERPRINT_HI;
    output.OpenPBROpaque.baseWeight = vivid_v0002;
    output.OpenPBROpaque.baseColor = vivid_v0004;
    output.OpenPBROpaque.baseDiffuseRoughness = vivid_v0000;
    output.OpenPBROpaque.baseMetalness = vivid_v0000;
    output.OpenPBROpaque.specularWeight = vivid_v0002;
    output.OpenPBROpaque.specularColor = vivid_v0005;
    output.OpenPBROpaque.specularRoughness = vivid_v0001;
    output.OpenPBROpaque.specularIor = vivid_v0003;
    output.OpenPBROpaque.normalWS = vivid_v0006;
    output.OpenPBROpaque.emissionLuminance = vivid_v0000;
    output.OpenPBROpaque.emissionColor = vivid_v0005;
    output.ClosureCount = VIVID_OPENPBR_OPAQUE_CLOSURE_COUNT;
    output.LayerOperator = 0u;
    return output;
}

bool VividTryEvaluateAOTSurfaceProgram(
    const VividMaterialRuntimeHeader runtimeHeader,
    const VividMaterialProgramData programData,
    const VividAOTSurfaceContext context,
    out VividAOTDeferredExportContract deferredExportContract,
    out VividAOTSurfaceProgramOutput output)
{
    deferredExportContract = (VividAOTDeferredExportContract) 0;
    output = (VividAOTSurfaceProgramOutput) 0;
    if (programData.Version != VIVID_MATERIAL_PROGRAM_VERSION
        || programData.ParameterLayoutID
            != VIVIDMATERIALPARAMETERLAYOUTID_GENERIC_PARAMETER_LANES
        || programData.ResourceLayoutID
            != VIVIDMATERIALRESOURCELAYOUTID_GENERIC_RESOURCE_RECORDS)
        return false;
    switch (runtimeHeader.ProgramID)
    {
        case 0u:
        {
            const uint parameterLaneCount = 4u;
            const uint resourceCount = 1u;
            if (runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            deferredExportContract.Version = 2u;
            deferredExportContract.SurfaceSummaryAbi = 1u;
            deferredExportContract.DualSlabSidecarAbi = 0u;
            deferredExportContract.NativePayloadAbi = 0u;
            deferredExportContract.NativeProfileVersion = 0u;
            deferredExportContract.NativeProfileFingerprintLo = 0u;
            deferredExportContract.NativeProfileFingerprintHi = 0u;
            deferredExportContract.ShadingModelMask = 3u;
            deferredExportContract.LitClass = 2u;
            deferredExportContract.ExpectedClosureCount = 1u;
            deferredExportContract.Topology = 0u;
            deferredExportContract.PayloadFlags = 3u;
            deferredExportContract.PolicyFlags = 7u;
            output = VividEvaluateAOTSurface_215C5B2731CAFB52(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        case 1u:
        {
            const uint parameterLaneCount = 6u;
            const uint resourceCount = 2u;
            if (runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            deferredExportContract.Version = 2u;
            deferredExportContract.SurfaceSummaryAbi = 1u;
            deferredExportContract.DualSlabSidecarAbi = 1u;
            deferredExportContract.NativePayloadAbi = 0u;
            deferredExportContract.NativeProfileVersion = 0u;
            deferredExportContract.NativeProfileFingerprintLo = 0u;
            deferredExportContract.NativeProfileFingerprintHi = 0u;
            deferredExportContract.ShadingModelMask = 3u;
            deferredExportContract.LitClass = 4u;
            deferredExportContract.ExpectedClosureCount = 2u;
            deferredExportContract.Topology = 1u;
            deferredExportContract.PayloadFlags = 15u;
            deferredExportContract.PolicyFlags = 15u;
            output = VividEvaluateAOTSurface_130EA2D589CBAD8C(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        case 2u:
        {
            const uint parameterLaneCount = 6u;
            const uint resourceCount = 2u;
            if (runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            deferredExportContract.Version = 2u;
            deferredExportContract.SurfaceSummaryAbi = 1u;
            deferredExportContract.DualSlabSidecarAbi = 1u;
            deferredExportContract.NativePayloadAbi = 0u;
            deferredExportContract.NativeProfileVersion = 0u;
            deferredExportContract.NativeProfileFingerprintLo = 0u;
            deferredExportContract.NativeProfileFingerprintHi = 0u;
            deferredExportContract.ShadingModelMask = 3u;
            deferredExportContract.LitClass = 4u;
            deferredExportContract.ExpectedClosureCount = 2u;
            deferredExportContract.Topology = 2u;
            deferredExportContract.PayloadFlags = 15u;
            deferredExportContract.PolicyFlags = 15u;
            output = VividEvaluateAOTSurface_527E00D079249214(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        case 3u:
        {
            const uint parameterLaneCount = 4u;
            const uint resourceCount = 1u;
            if (runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            deferredExportContract.Version = 2u;
            deferredExportContract.SurfaceSummaryAbi = 1u;
            deferredExportContract.DualSlabSidecarAbi = 0u;
            deferredExportContract.NativePayloadAbi = 0u;
            deferredExportContract.NativeProfileVersion = 0u;
            deferredExportContract.NativeProfileFingerprintLo = 0u;
            deferredExportContract.NativeProfileFingerprintHi = 0u;
            deferredExportContract.ShadingModelMask = 1u;
            deferredExportContract.LitClass = 2u;
            deferredExportContract.ExpectedClosureCount = 1u;
            deferredExportContract.Topology = 0u;
            deferredExportContract.PayloadFlags = 3u;
            deferredExportContract.PolicyFlags = 7u;
            output = VividEvaluateAOTSurface_FCBA57D9E58B9CDC(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        case 4u:
        {
            const uint parameterLaneCount = 0u;
            const uint resourceCount = 0u;
            if (runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            deferredExportContract.Version = 2u;
            deferredExportContract.SurfaceSummaryAbi = 0u;
            deferredExportContract.DualSlabSidecarAbi = 0u;
            deferredExportContract.NativePayloadAbi = 1u;
            deferredExportContract.NativeProfileVersion = 1u;
            deferredExportContract.NativeProfileFingerprintLo = 3867404148u;
            deferredExportContract.NativeProfileFingerprintHi = 369231404u;
            deferredExportContract.ShadingModelMask = 4u;
            deferredExportContract.LitClass = 6u;
            deferredExportContract.ExpectedClosureCount = 1u;
            deferredExportContract.Topology = 0u;
            deferredExportContract.PayloadFlags = 16u;
            deferredExportContract.PolicyFlags = 0u;
            output = VividEvaluateAOTSurface_30B108E514D38D6E(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            if (!VividIsAOTDeferredExportContractSupported(deferredExportContract)
                || output.Profile != VIVID_AOT_SURFACE_PROFILE_OPENPBR_OPAQUE
                || output.NativeProfileVersion != deferredExportContract.NativeProfileVersion
                || output.NativeProfileFingerprintLo != deferredExportContract.NativeProfileFingerprintLo
                || output.NativeProfileFingerprintHi != deferredExportContract.NativeProfileFingerprintHi
                || output.ClosureCount != deferredExportContract.ExpectedClosureCount
                || output.LayerOperator != deferredExportContract.Topology
                || VividValidateOpenPBROpaqueInputs(output.OpenPBROpaque, 0u) != 0u)
                return false;
            return true;
        }
        default:
            return false;
    }
}

#endif // VIVID_MATERIAL_SURFACE_AOT_GENERATED_INCLUDED
