// <auto-generated by MaterialSurfaceHlslGenerator>
// Generated from canonical Surface Stage LIR and Deferred Export contracts; do not edit.
#ifndef VIVID_MATERIAL_SURFACE_AOT_GENERATED_INCLUDED
#define VIVID_MATERIAL_SURFACE_AOT_GENERATED_INCLUDED

#define VIVID_MATERIAL_SURFACE_HLSL_BACKEND_VERSION 5u

#ifndef VIVID_MATERIAL_CATALOG_MANIFEST_INCLUDED
#define VIVID_MATERIAL_CATALOG_MANIFEST_INCLUDED
#define VIVID_MATERIAL_CATALOG_MANIFEST_VERSION 3u
#define VIVID_MATERIAL_CATALOG_MANIFEST_HASH_LO 0x3E14D387u
#define VIVID_MATERIAL_CATALOG_MANIFEST_HASH_HI 0x348D9F37u
#define VIVID_MATERIAL_CATALOG_PROGRAM_TABLE_LENGTH 4u
#elif VIVID_MATERIAL_CATALOG_MANIFEST_VERSION != 3u || VIVID_MATERIAL_CATALOG_MANIFEST_HASH_LO != 0x3E14D387u || VIVID_MATERIAL_CATALOG_MANIFEST_HASH_HI != 0x348D9F37u || VIVID_MATERIAL_CATALOG_PROGRAM_TABLE_LENGTH != 4u
#error Material dispatchers use different frozen catalog manifests.
#endif

#define VIVID_AOT_DEFERRED_EXPORT_CONTRACT_VERSION 1u
#define VIVID_AOT_DEFERRED_EXPORT_SURFACE_SUMMARY_ABI_V1 1u
#define VIVID_AOT_DEFERRED_EXPORT_SIDECAR_ABI_NONE 0u
#define VIVID_AOT_DEFERRED_EXPORT_SIDECAR_ABI_DUAL_SLAB_V1 1u
#define VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_STANDARD_LIT 1u
#define VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_UNLIT 2u
#define VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_NONE 0u
#define VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_FAST_SLAB 2u
#define VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_DUAL_SLAB 4u
#define VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_NONE 0u
#define VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_HORIZONTAL_MIX 1u
#define VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_VERTICAL_LAYER 2u
#define VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_SURFACE_SUMMARY 1u
#define VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_DIFFUSE_IRRADIANCE 2u
#define VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_DUAL_SLAB_SIDECAR 4u
#define VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_SHARED_NORMAL_AO 8u
#define VIVID_AOT_DEFERRED_EXPORT_POLICY_DYNAMIC_DIFFUSE_IRRADIANCE 1u
#define VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_SSR_ON_FAST_SLAB 2u
#define VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_DECALS 4u
#define VIVID_AOT_DEFERRED_EXPORT_POLICY_FAST_SLAB_WHEN_SIDECAR_EMPTY 8u

struct VividAOTDeferredExportContract
{
    uint Version;
    uint SurfaceSummaryAbi;
    uint DualSlabSidecarAbi;
    uint ShadingModelMask;
    uint LitClass;
    uint ExpectedClosureCount;
    uint Topology;
    uint PayloadFlags;
    uint PolicyFlags;
};

bool VividAOTDeferredExportHasShadingModel(
    const VividAOTDeferredExportContract contract,
    const uint shadingModel)
{
    return (contract.ShadingModelMask & shadingModel) == shadingModel;
}

bool VividAOTDeferredExportHasPayload(
    const VividAOTDeferredExportContract contract,
    const uint payload)
{
    return (contract.PayloadFlags & payload) == payload;
}

bool VividAOTDeferredExportHasPolicy(
    const VividAOTDeferredExportContract contract,
    const uint policy)
{
    return (contract.PolicyFlags & policy) == policy;
}

bool VividIsAOTDeferredExportContractSupported(
    const VividAOTDeferredExportContract contract)
{
    if (contract.Version != VIVID_AOT_DEFERRED_EXPORT_CONTRACT_VERSION
        || contract.SurfaceSummaryAbi != VIVID_AOT_DEFERRED_EXPORT_SURFACE_SUMMARY_ABI_V1)
        return false;

    const uint knownShadingModels =
        VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_STANDARD_LIT
        | VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_UNLIT;
    if (contract.ShadingModelMask == 0u
        || (contract.ShadingModelMask & ~knownShadingModels) != 0u)
        return false;

    const bool isSingle = contract.Topology
        == VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_NONE;
    const bool isDual = contract.Topology
            == VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_HORIZONTAL_MIX
        || contract.Topology
            == VIVID_AOT_DEFERRED_EXPORT_TOPOLOGY_VERTICAL_LAYER;
    if ((!isSingle && !isDual)
        || contract.ExpectedClosureCount != (isDual ? 2u : 1u))
        return false;

    const uint corePayload =
        VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_SURFACE_SUMMARY
        | VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_DIFFUSE_IRRADIANCE;
    const uint knownPayload = corePayload
        | VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_DUAL_SLAB_SIDECAR
        | VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_SHARED_NORMAL_AO;
    if ((contract.PayloadFlags & corePayload) != corePayload
        || (contract.PayloadFlags & ~knownPayload) != 0u)
        return false;

    const uint knownPolicy =
        VIVID_AOT_DEFERRED_EXPORT_POLICY_DYNAMIC_DIFFUSE_IRRADIANCE
        | VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_SSR_ON_FAST_SLAB
        | VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_DECALS
        | VIVID_AOT_DEFERRED_EXPORT_POLICY_FAST_SLAB_WHEN_SIDECAR_EMPTY;
    if ((contract.PolicyFlags & ~knownPolicy) != 0u
        || !VividAOTDeferredExportHasPolicy(
            contract,
            VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_DECALS))
        return false;

    const bool supportsLit = VividAOTDeferredExportHasShadingModel(
        contract,
        VIVID_AOT_DEFERRED_EXPORT_SHADING_MODEL_STANDARD_LIT);
    const uint expectedLitClass = !supportsLit
        ? VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_NONE
        : isDual
            ? VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_DUAL_SLAB
            : VIVID_AOT_DEFERRED_EXPORT_LIT_CLASS_FAST_SLAB;
    if (contract.LitClass != expectedLitClass)
        return false;

    const bool expectsDualSidecar = supportsLit && isDual;
    const bool hasDualSidecar = VividAOTDeferredExportHasPayload(
        contract,
        VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_DUAL_SLAB_SIDECAR);
    const bool sharesNormalAO = VividAOTDeferredExportHasPayload(
        contract,
        VIVID_AOT_DEFERRED_EXPORT_PAYLOAD_SHARED_NORMAL_AO);
    const bool hasDualSidecarAbi = contract.DualSlabSidecarAbi
        == VIVID_AOT_DEFERRED_EXPORT_SIDECAR_ABI_DUAL_SLAB_V1;
    if ((contract.DualSlabSidecarAbi
            != VIVID_AOT_DEFERRED_EXPORT_SIDECAR_ABI_NONE
            && !hasDualSidecarAbi)
        || hasDualSidecar != expectsDualSidecar
        || sharesNormalAO != isDual
        || hasDualSidecarAbi != expectsDualSidecar)
        return false;

    const uint litPolicies =
        VIVID_AOT_DEFERRED_EXPORT_POLICY_DYNAMIC_DIFFUSE_IRRADIANCE
        | VIVID_AOT_DEFERRED_EXPORT_POLICY_RECEIVE_SSR_ON_FAST_SLAB;
    const uint activeLitPolicies = contract.PolicyFlags & litPolicies;
    const bool hasFastFallback = VividAOTDeferredExportHasPolicy(
        contract,
        VIVID_AOT_DEFERRED_EXPORT_POLICY_FAST_SLAB_WHEN_SIDECAR_EMPTY);
    return activeLitPolicies == (supportsLit ? litPolicies : 0u)
        && hasFastFallback == expectsDualSidecar;
}

struct VividAOTSurfaceContext
{
    float2 UV0;
    float2 UV0Ddx;
    float2 UV0Ddy;
    float3 GeometryNormalWS;
    float4 GeometryTangentWS;
    float4 PositionCS;
};

struct VividAOTSurfaceSlabValues
{
    float4 BaseColor;
    float PerceptualRoughness;
    float Metallic;
    float3 NormalWS;
    float4 TangentWS;
    float3 NormalTS;
    float AmbientOcclusion;
    uint HasNormal;
    uint FeatureMask;
};

struct VividAOTSurfaceProgramOutput
{
    VividAOTSurfaceSlabValues BaseSlab;
    VividAOTSurfaceSlabValues TopSlab;
    float3 Emission;
    float LayerWeight;
    uint ClosureCount;
    uint LayerOperator;
};

// Surface AOT HLSL artifact v4, backend v5.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_09A22006CB295347(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTSurfaceContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float3 vivid_v0001 = context.GeometryNormalWS;
    const float4 vivid_v0002 = context.GeometryTangentWS;
    const float vivid_v0003 = VividLoadMaterialFloat(parameterAddress, 11u);
    const float vivid_v0004 = VividLoadMaterialFloat(parameterAddress, 12u);
    const float3 vivid_v0005 = VividLoadMaterialFloat3(parameterAddress, 8u);
    const float4 vivid_v0006 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float2 vivid_v0008 = context.UV0Ddx;
    const float2 vivid_v0009 = context.UV0Ddy;
    const VividMaterialResourceData vivid_sample_resource_10 = PullMaterialResourceData(resourceAddress + 0u);
    const VividSurfaceBindingData vivid_sample_binding_10 = vivid_sample_resource_10.SurfaceBinding;
    const VividSlabMaterialData vivid_sample_slab_10 = VividCreateSlabMaterialData(vivid_sample_resource_10);
    const float2 vivid_sample_uv_10 = vivid_v0000 * vivid_sample_slab_10.TextureTilingOffset.xy + vivid_sample_slab_10.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_10 = vivid_v0008 * vivid_sample_slab_10.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_10 = vivid_v0009 * vivid_sample_slab_10.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_10 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_10, vivid_sample_uv_10, vivid_sample_ddx_10, vivid_sample_ddy_10, context.PositionCS);
    const float4 vivid_v0010 = VividSampleBaseColorGrad(vivid_sample_binding_10, vivid_sample_context_10);
    const float4 vivid_v0011 = (vivid_v0006 * vivid_v0010);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0011;
    output.BaseSlab.PerceptualRoughness = vivid_v0004;
    output.BaseSlab.Metallic = vivid_v0003;
    output.BaseSlab.NormalWS = vivid_v0001;
    output.BaseSlab.TangentWS = vivid_v0002;
    output.BaseSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_base_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_10,
        vivid_sample_binding_10,
        vivid_sample_context_10,
        true,
        true,
        output.BaseSlab.BaseColor.rgb,
        output.BaseSlab.PerceptualRoughness,
        output.BaseSlab.Metallic);
    output.BaseSlab.PerceptualRoughness = vivid_base_slab_detail.PerceptualRoughness;
    output.BaseSlab.Metallic = vivid_base_slab_detail.Metallic;
    output.BaseSlab.NormalTS = vivid_base_slab_detail.NormalTS;
    output.BaseSlab.AmbientOcclusion = vivid_base_slab_detail.AmbientOcclusion;
    output.BaseSlab.HasNormal = vivid_base_slab_detail.HasNormal;
    output.ClosureCount = 1u;
    output.LayerOperator = 0u;
    output.Emission = vivid_v0005;
    return output;
}

// Surface AOT HLSL artifact v4, backend v5.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_337BBB8AC4DBB6FA(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTSurfaceContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float3 vivid_v0001 = context.GeometryNormalWS;
    const float4 vivid_v0002 = context.GeometryTangentWS;
    const float vivid_v0003 = VividLoadMaterialFloat(parameterAddress, 11u);
    const float vivid_v0004 = VividLoadMaterialFloat(parameterAddress, 12u);
    const float vivid_v0005 = VividLoadMaterialFloat(parameterAddress, 13u);
    const float vivid_v0006 = VividLoadMaterialFloat(parameterAddress, 20u);
    const float vivid_v0007 = VividLoadMaterialFloat(parameterAddress, 21u);
    const float3 vivid_v0008 = VividLoadMaterialFloat3(parameterAddress, 8u);
    const float4 vivid_v0009 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float4 vivid_v0010 = VividLoadMaterialFloat4(parameterAddress, 16u);
    const float2 vivid_v0013 = context.UV0Ddx;
    const float2 vivid_v0014 = context.UV0Ddy;
    const VividMaterialResourceData vivid_sample_resource_15 = PullMaterialResourceData(resourceAddress + 0u);
    const VividSurfaceBindingData vivid_sample_binding_15 = vivid_sample_resource_15.SurfaceBinding;
    const VividSlabMaterialData vivid_sample_slab_15 = VividCreateSlabMaterialData(vivid_sample_resource_15);
    const float2 vivid_sample_uv_15 = vivid_v0000 * vivid_sample_slab_15.TextureTilingOffset.xy + vivid_sample_slab_15.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_15 = vivid_v0013 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_15 = vivid_v0014 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_15 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_15, vivid_sample_uv_15, vivid_sample_ddx_15, vivid_sample_ddy_15, context.PositionCS);
    const float4 vivid_v0015 = VividSampleBaseColorGrad(vivid_sample_binding_15, vivid_sample_context_15);
    const VividMaterialResourceData vivid_sample_resource_16 = PullMaterialResourceData(resourceAddress + 1u);
    const VividSurfaceBindingData vivid_sample_binding_16 = vivid_sample_resource_16.SurfaceBinding;
    const VividSlabMaterialData vivid_sample_slab_16 = VividCreateSlabMaterialData(vivid_sample_resource_16);
    const float2 vivid_sample_uv_16 = vivid_v0000 * vivid_sample_slab_16.TextureTilingOffset.xy + vivid_sample_slab_16.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_16 = vivid_v0013 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_16 = vivid_v0014 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_16 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_16, vivid_sample_uv_16, vivid_sample_ddx_16, vivid_sample_ddy_16, context.PositionCS);
    const float4 vivid_v0016 = VividSampleBaseColorGrad(vivid_sample_binding_16, vivid_sample_context_16);
    const float4 vivid_v0017 = (vivid_v0009 * vivid_v0015);
    const float4 vivid_v0018 = (vivid_v0010 * vivid_v0016);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0017;
    output.BaseSlab.PerceptualRoughness = vivid_v0005;
    output.BaseSlab.Metallic = vivid_v0004;
    output.BaseSlab.NormalWS = vivid_v0001;
    output.BaseSlab.TangentWS = vivid_v0002;
    output.BaseSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_base_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_15,
        vivid_sample_binding_15,
        vivid_sample_context_15,
        true,
        true,
        output.BaseSlab.BaseColor.rgb,
        output.BaseSlab.PerceptualRoughness,
        output.BaseSlab.Metallic);
    output.BaseSlab.PerceptualRoughness = vivid_base_slab_detail.PerceptualRoughness;
    output.BaseSlab.Metallic = vivid_base_slab_detail.Metallic;
    output.BaseSlab.NormalTS = vivid_base_slab_detail.NormalTS;
    output.BaseSlab.AmbientOcclusion = vivid_base_slab_detail.AmbientOcclusion;
    output.BaseSlab.HasNormal = vivid_base_slab_detail.HasNormal;
    output.TopSlab.BaseColor = vivid_v0018;
    output.TopSlab.PerceptualRoughness = vivid_v0007;
    output.TopSlab.Metallic = vivid_v0006;
    output.TopSlab.NormalWS = vivid_v0001;
    output.TopSlab.TangentWS = vivid_v0002;
    output.TopSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_top_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_16,
        vivid_sample_binding_16,
        vivid_sample_context_16,
        true,
        true,
        output.TopSlab.BaseColor.rgb,
        output.TopSlab.PerceptualRoughness,
        output.TopSlab.Metallic);
    output.TopSlab.PerceptualRoughness = vivid_top_slab_detail.PerceptualRoughness;
    output.TopSlab.Metallic = vivid_top_slab_detail.Metallic;
    output.TopSlab.NormalTS = vivid_top_slab_detail.NormalTS;
    output.TopSlab.AmbientOcclusion = vivid_top_slab_detail.AmbientOcclusion;
    output.TopSlab.HasNormal = vivid_top_slab_detail.HasNormal;
    output.LayerWeight = vivid_v0003;
    output.ClosureCount = 2u;
    output.LayerOperator = 1u;
    output.Emission = vivid_v0008;
    return output;
}

// Surface AOT HLSL artifact v4, backend v5.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_1AC9F20550648A1A(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTSurfaceContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float3 vivid_v0001 = context.GeometryNormalWS;
    const float4 vivid_v0002 = context.GeometryTangentWS;
    const float vivid_v0003 = VividLoadMaterialFloat(parameterAddress, 11u);
    const float vivid_v0004 = VividLoadMaterialFloat(parameterAddress, 12u);
    const float vivid_v0005 = VividLoadMaterialFloat(parameterAddress, 13u);
    const float vivid_v0006 = VividLoadMaterialFloat(parameterAddress, 20u);
    const float vivid_v0007 = VividLoadMaterialFloat(parameterAddress, 21u);
    const float3 vivid_v0008 = VividLoadMaterialFloat3(parameterAddress, 8u);
    const float4 vivid_v0009 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float4 vivid_v0010 = VividLoadMaterialFloat4(parameterAddress, 16u);
    const float2 vivid_v0013 = context.UV0Ddx;
    const float2 vivid_v0014 = context.UV0Ddy;
    const VividMaterialResourceData vivid_sample_resource_15 = PullMaterialResourceData(resourceAddress + 0u);
    const VividSurfaceBindingData vivid_sample_binding_15 = vivid_sample_resource_15.SurfaceBinding;
    const VividSlabMaterialData vivid_sample_slab_15 = VividCreateSlabMaterialData(vivid_sample_resource_15);
    const float2 vivid_sample_uv_15 = vivid_v0000 * vivid_sample_slab_15.TextureTilingOffset.xy + vivid_sample_slab_15.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_15 = vivid_v0013 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_15 = vivid_v0014 * vivid_sample_slab_15.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_15 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_15, vivid_sample_uv_15, vivid_sample_ddx_15, vivid_sample_ddy_15, context.PositionCS);
    const float4 vivid_v0015 = VividSampleBaseColorGrad(vivid_sample_binding_15, vivid_sample_context_15);
    const VividMaterialResourceData vivid_sample_resource_16 = PullMaterialResourceData(resourceAddress + 1u);
    const VividSurfaceBindingData vivid_sample_binding_16 = vivid_sample_resource_16.SurfaceBinding;
    const VividSlabMaterialData vivid_sample_slab_16 = VividCreateSlabMaterialData(vivid_sample_resource_16);
    const float2 vivid_sample_uv_16 = vivid_v0000 * vivid_sample_slab_16.TextureTilingOffset.xy + vivid_sample_slab_16.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_16 = vivid_v0013 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_16 = vivid_v0014 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_16 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_16, vivid_sample_uv_16, vivid_sample_ddx_16, vivid_sample_ddy_16, context.PositionCS);
    const float4 vivid_v0016 = VividSampleBaseColorGrad(vivid_sample_binding_16, vivid_sample_context_16);
    const float4 vivid_v0017 = (vivid_v0009 * vivid_v0015);
    const float4 vivid_v0018 = (vivid_v0010 * vivid_v0016);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0017;
    output.BaseSlab.PerceptualRoughness = vivid_v0005;
    output.BaseSlab.Metallic = vivid_v0004;
    output.BaseSlab.NormalWS = vivid_v0001;
    output.BaseSlab.TangentWS = vivid_v0002;
    output.BaseSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_base_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_15,
        vivid_sample_binding_15,
        vivid_sample_context_15,
        true,
        true,
        output.BaseSlab.BaseColor.rgb,
        output.BaseSlab.PerceptualRoughness,
        output.BaseSlab.Metallic);
    output.BaseSlab.PerceptualRoughness = vivid_base_slab_detail.PerceptualRoughness;
    output.BaseSlab.Metallic = vivid_base_slab_detail.Metallic;
    output.BaseSlab.NormalTS = vivid_base_slab_detail.NormalTS;
    output.BaseSlab.AmbientOcclusion = vivid_base_slab_detail.AmbientOcclusion;
    output.BaseSlab.HasNormal = vivid_base_slab_detail.HasNormal;
    output.TopSlab.BaseColor = vivid_v0018;
    output.TopSlab.PerceptualRoughness = vivid_v0007;
    output.TopSlab.Metallic = vivid_v0006;
    output.TopSlab.NormalWS = vivid_v0001;
    output.TopSlab.TangentWS = vivid_v0002;
    output.TopSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_top_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_16,
        vivid_sample_binding_16,
        vivid_sample_context_16,
        true,
        true,
        output.TopSlab.BaseColor.rgb,
        output.TopSlab.PerceptualRoughness,
        output.TopSlab.Metallic);
    output.TopSlab.PerceptualRoughness = vivid_top_slab_detail.PerceptualRoughness;
    output.TopSlab.Metallic = vivid_top_slab_detail.Metallic;
    output.TopSlab.NormalTS = vivid_top_slab_detail.NormalTS;
    output.TopSlab.AmbientOcclusion = vivid_top_slab_detail.AmbientOcclusion;
    output.TopSlab.HasNormal = vivid_top_slab_detail.HasNormal;
    output.LayerWeight = vivid_v0003;
    output.ClosureCount = 2u;
    output.LayerOperator = 2u;
    output.Emission = vivid_v0008;
    return output;
}

// Surface AOT HLSL artifact v4, backend v5.
VividAOTSurfaceProgramOutput VividEvaluateAOTSurface_3FA009788988936A(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTSurfaceContext context)
{
    const float vivid_v0000 = asfloat(0x3F000000u);
    const float3 vivid_v0001 = float3(asfloat(0x3D4CCCCDu), asfloat(0x3DCCCCCDu), asfloat(0x3E19999Au));
    const float4 vivid_v0002 = float4(asfloat(0x3F000000u), asfloat(0x3E800000u), asfloat(0x3F400000u), asfloat(0x3F800000u));
    const float2 vivid_v0003 = context.UV0;
    const float3 vivid_v0004 = context.GeometryNormalWS;
    const float4 vivid_v0005 = context.GeometryTangentWS;
    const float vivid_v0006 = VividLoadMaterialFloat(parameterAddress, 11u);
    const float vivid_v0007 = VividLoadMaterialFloat(parameterAddress, 12u);
    const float3 vivid_v0008 = VividLoadMaterialFloat3(parameterAddress, 8u);
    const float4 vivid_v0009 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float2 vivid_v0011 = context.UV0Ddx;
    const float2 vivid_v0012 = context.UV0Ddy;
    const float3 vivid_v0013 = (vivid_v0001 + vivid_v0008);
    const float vivid_v0014 = (vivid_v0000 * vivid_v0006);
    const float vivid_v0015 = (1.0f - vivid_v0007);
    const VividMaterialResourceData vivid_sample_resource_16 = PullMaterialResourceData(resourceAddress + 0u);
    const VividSurfaceBindingData vivid_sample_binding_16 = vivid_sample_resource_16.SurfaceBinding;
    const VividSlabMaterialData vivid_sample_slab_16 = VividCreateSlabMaterialData(vivid_sample_resource_16);
    const float2 vivid_sample_uv_16 = vivid_v0003 * vivid_sample_slab_16.TextureTilingOffset.xy + vivid_sample_slab_16.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_16 = vivid_v0011 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_16 = vivid_v0012 * vivid_sample_slab_16.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_16 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_16, vivid_sample_uv_16, vivid_sample_ddx_16, vivid_sample_ddy_16, context.PositionCS);
    const float4 vivid_v0016 = VividSampleBaseColorGrad(vivid_sample_binding_16, vivid_sample_context_16);
    const float vivid_v0017 = saturate(vivid_v0014);
    const float4 vivid_v0018 = (vivid_v0009 * vivid_v0016);
    const float4 vivid_v0019 = (vivid_v0002 * vivid_v0018);

    VividAOTSurfaceProgramOutput output = (VividAOTSurfaceProgramOutput) 0;
    output.BaseSlab.BaseColor = vivid_v0019;
    output.BaseSlab.PerceptualRoughness = vivid_v0015;
    output.BaseSlab.Metallic = vivid_v0017;
    output.BaseSlab.NormalWS = vivid_v0004;
    output.BaseSlab.TangentWS = vivid_v0005;
    output.BaseSlab.FeatureMask = 7u;
    const VividEvaluatedSlabSurface vivid_base_slab_detail = VividEvaluateAOTSlabSurfaceDetail(
        vivid_sample_slab_16,
        vivid_sample_binding_16,
        vivid_sample_context_16,
        true,
        true,
        output.BaseSlab.BaseColor.rgb,
        output.BaseSlab.PerceptualRoughness,
        output.BaseSlab.Metallic);
    output.BaseSlab.PerceptualRoughness = vivid_base_slab_detail.PerceptualRoughness;
    output.BaseSlab.Metallic = vivid_base_slab_detail.Metallic;
    output.BaseSlab.NormalTS = vivid_base_slab_detail.NormalTS;
    output.BaseSlab.AmbientOcclusion = vivid_base_slab_detail.AmbientOcclusion;
    output.BaseSlab.HasNormal = vivid_base_slab_detail.HasNormal;
    output.ClosureCount = 1u;
    output.LayerOperator = 0u;
    output.Emission = vivid_v0013;
    return output;
}

bool VividTryEvaluateAOTSurfaceProgram(
    const VividMaterialRuntimeHeader runtimeHeader,
    const VividMaterialProgramData programData,
    const VividAOTSurfaceContext context,
    out VividAOTDeferredExportContract deferredExportContract,
    out VividAOTSurfaceProgramOutput output)
{
    deferredExportContract = (VividAOTDeferredExportContract) 0;
    output = (VividAOTSurfaceProgramOutput) 0;
    if (programData.Version != VIVID_MATERIAL_PROGRAM_VERSION
        || programData.ParameterLayoutID
            != VIVIDMATERIALPARAMETERLAYOUTID_GENERIC_PARAMETER_LANES
        || programData.ResourceLayoutID
            != VIVIDMATERIALRESOURCELAYOUTID_GENERIC_RESOURCE_RECORDS)
        return false;
    switch (runtimeHeader.ProgramID)
    {
        case 0u:
        {
            const uint parameterLaneCount = 4u;
            const uint resourceCount = 1u;
            if (runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            deferredExportContract.Version = 1u;
            deferredExportContract.SurfaceSummaryAbi = 1u;
            deferredExportContract.DualSlabSidecarAbi = 0u;
            deferredExportContract.ShadingModelMask = 3u;
            deferredExportContract.LitClass = 2u;
            deferredExportContract.ExpectedClosureCount = 1u;
            deferredExportContract.Topology = 0u;
            deferredExportContract.PayloadFlags = 3u;
            deferredExportContract.PolicyFlags = 7u;
            output = VividEvaluateAOTSurface_09A22006CB295347(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        case 1u:
        {
            const uint parameterLaneCount = 6u;
            const uint resourceCount = 2u;
            if (runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            deferredExportContract.Version = 1u;
            deferredExportContract.SurfaceSummaryAbi = 1u;
            deferredExportContract.DualSlabSidecarAbi = 1u;
            deferredExportContract.ShadingModelMask = 3u;
            deferredExportContract.LitClass = 4u;
            deferredExportContract.ExpectedClosureCount = 2u;
            deferredExportContract.Topology = 1u;
            deferredExportContract.PayloadFlags = 15u;
            deferredExportContract.PolicyFlags = 15u;
            output = VividEvaluateAOTSurface_337BBB8AC4DBB6FA(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        case 2u:
        {
            const uint parameterLaneCount = 6u;
            const uint resourceCount = 2u;
            if (runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            deferredExportContract.Version = 1u;
            deferredExportContract.SurfaceSummaryAbi = 1u;
            deferredExportContract.DualSlabSidecarAbi = 1u;
            deferredExportContract.ShadingModelMask = 3u;
            deferredExportContract.LitClass = 4u;
            deferredExportContract.ExpectedClosureCount = 2u;
            deferredExportContract.Topology = 2u;
            deferredExportContract.PayloadFlags = 15u;
            deferredExportContract.PolicyFlags = 15u;
            output = VividEvaluateAOTSurface_1AC9F20550648A1A(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        case 3u:
        {
            const uint parameterLaneCount = 4u;
            const uint resourceCount = 1u;
            if (runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            deferredExportContract.Version = 1u;
            deferredExportContract.SurfaceSummaryAbi = 1u;
            deferredExportContract.DualSlabSidecarAbi = 0u;
            deferredExportContract.ShadingModelMask = 3u;
            deferredExportContract.LitClass = 2u;
            deferredExportContract.ExpectedClosureCount = 1u;
            deferredExportContract.Topology = 0u;
            deferredExportContract.PayloadFlags = 3u;
            deferredExportContract.PolicyFlags = 7u;
            output = VividEvaluateAOTSurface_3FA009788988936A(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        default:
            return false;
    }
}

#endif // VIVID_MATERIAL_SURFACE_AOT_GENERATED_INCLUDED
