// <auto-generated by MaterialCoverageHlslGenerator>
// Generated from canonical Coverage Stage LIR; do not edit.
#ifndef VIVID_MATERIAL_COVERAGE_AOT_GENERATED_INCLUDED
#define VIVID_MATERIAL_COVERAGE_AOT_GENERATED_INCLUDED

#define VIVID_MATERIAL_COVERAGE_HLSL_BACKEND_VERSION 5u

// Expected Material Program artifact set: v2 0x813CC91495317BA3
#include "VividMaterialProgramCatalogStamp.generated.hlsl"
#if !defined(VIVID_MATERIAL_PUBLISHED_ARTIFACT_SET_INCLUDED)
#error Missing published Material Program Catalog stamp for Coverage dispatcher.
#elif !defined(VIVID_MATERIAL_PUBLISHED_ARTIFACT_SET_V00000002_H813CC91495317BA3)
#error Coverage dispatcher does not match the published Material Program Catalog artifact set.
#endif

#ifndef VIVID_MATERIAL_CATALOG_MANIFEST_INCLUDED
#define VIVID_MATERIAL_CATALOG_MANIFEST_INCLUDED
#define VIVID_MATERIAL_CATALOG_MANIFEST_V00000005_H57B7B026DE009361_N00000004 1
#elif !defined(VIVID_MATERIAL_CATALOG_MANIFEST_V00000005_H57B7B026DE009361_N00000004)
#error Material dispatchers use different frozen catalog manifests.
#endif

struct VividAOTCoverageContext
{
    float2 UV0;
    float2 UV0Ddx;
    float2 UV0Ddy;
};

// Coverage AOT HLSL artifact v2, backend v5.
VividMaterialCoverageEvaluation VividEvaluateAOTCoverage_73E31B25B101D550(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTCoverageContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float vivid_v0001 = VividLoadMaterialFloat(parameterAddress, 0u);
    const float4 vivid_v0002 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float2 vivid_v0004 = context.UV0Ddx;
    const float2 vivid_v0005 = context.UV0Ddy;
    const VividMaterialResourceData vivid_sample_resource_6 = PullMaterialResourceData(resourceAddress + 0u);
    VividSurfaceBindingData vivid_sample_binding_6;
    vivid_sample_binding_6.BaseColorResource = vivid_sample_resource_6.BaseColorResource;
    vivid_sample_binding_6.NormalResource = vivid_sample_resource_6.NormalResource;
    vivid_sample_binding_6.MaskResource = vivid_sample_resource_6.MaskResource;
    vivid_sample_binding_6.Flags = vivid_sample_resource_6.SurfaceBindingFlags;
    vivid_sample_binding_6.UVScaleBias = vivid_sample_resource_6.UVScaleBias;
    const VividSlabMaterialData vivid_sample_slab_6 = VividCreateSlabMaterialData(vivid_sample_resource_6);
    const float2 vivid_sample_uv_6 = vivid_v0000 * vivid_sample_slab_6.TextureTilingOffset.xy + vivid_sample_slab_6.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_6 = vivid_v0004 * vivid_sample_slab_6.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_6 = vivid_v0005 * vivid_sample_slab_6.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_6 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_6, vivid_sample_uv_6, vivid_sample_ddx_6, vivid_sample_ddy_6);
    const float4 vivid_v0006 = VividSampleBaseColorGrad(vivid_sample_binding_6, vivid_sample_context_6);
    const float4 vivid_v0007 = (vivid_v0002 * vivid_v0006);
    const float vivid_v0008 = vivid_v0007.w;

    VividMaterialCoverageEvaluation output;
    output.Coverage = vivid_v0008;
    output.AlphaClipThreshold = vivid_v0001;
    return output;
}

// Coverage AOT HLSL artifact v2, backend v5.
VividMaterialCoverageEvaluation VividEvaluateAOTCoverage_1402C703249979FA(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTCoverageContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float vivid_v0001 = VividLoadMaterialFloat(parameterAddress, 0u);
    const float4 vivid_v0002 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float2 vivid_v0004 = context.UV0Ddx;
    const float2 vivid_v0005 = context.UV0Ddy;
    const VividMaterialResourceData vivid_sample_resource_6 = PullMaterialResourceData(resourceAddress + 0u);
    VividSurfaceBindingData vivid_sample_binding_6;
    vivid_sample_binding_6.BaseColorResource = vivid_sample_resource_6.BaseColorResource;
    vivid_sample_binding_6.NormalResource = vivid_sample_resource_6.NormalResource;
    vivid_sample_binding_6.MaskResource = vivid_sample_resource_6.MaskResource;
    vivid_sample_binding_6.Flags = vivid_sample_resource_6.SurfaceBindingFlags;
    vivid_sample_binding_6.UVScaleBias = vivid_sample_resource_6.UVScaleBias;
    const VividSlabMaterialData vivid_sample_slab_6 = VividCreateSlabMaterialData(vivid_sample_resource_6);
    const float2 vivid_sample_uv_6 = vivid_v0000 * vivid_sample_slab_6.TextureTilingOffset.xy + vivid_sample_slab_6.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_6 = vivid_v0004 * vivid_sample_slab_6.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_6 = vivid_v0005 * vivid_sample_slab_6.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_6 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_6, vivid_sample_uv_6, vivid_sample_ddx_6, vivid_sample_ddy_6);
    const float4 vivid_v0006 = VividSampleBaseColorGrad(vivid_sample_binding_6, vivid_sample_context_6);
    const float4 vivid_v0007 = (vivid_v0002 * vivid_v0006);
    const float vivid_v0008 = vivid_v0007.w;

    VividMaterialCoverageEvaluation output;
    output.Coverage = vivid_v0008;
    output.AlphaClipThreshold = vivid_v0001;
    return output;
}

// Coverage AOT HLSL artifact v2, backend v5.
VividMaterialCoverageEvaluation VividEvaluateAOTCoverage_319E5482AA666435(
    const uint parameterAddress,
    const uint resourceAddress,
    const VividAOTCoverageContext context)
{
    const float vivid_v0000 = asfloat(0x3F000000u);
    const float2 vivid_v0001 = context.UV0;
    const float vivid_v0002 = VividLoadMaterialFloat(parameterAddress, 0u);
    const float4 vivid_v0003 = VividLoadMaterialFloat4(parameterAddress, 4u);
    const float2 vivid_v0005 = context.UV0Ddx;
    const float2 vivid_v0006 = context.UV0Ddy;
    const VividMaterialResourceData vivid_sample_resource_7 = PullMaterialResourceData(resourceAddress + 0u);
    VividSurfaceBindingData vivid_sample_binding_7;
    vivid_sample_binding_7.BaseColorResource = vivid_sample_resource_7.BaseColorResource;
    vivid_sample_binding_7.NormalResource = vivid_sample_resource_7.NormalResource;
    vivid_sample_binding_7.MaskResource = vivid_sample_resource_7.MaskResource;
    vivid_sample_binding_7.Flags = vivid_sample_resource_7.SurfaceBindingFlags;
    vivid_sample_binding_7.UVScaleBias = vivid_sample_resource_7.UVScaleBias;
    const VividSlabMaterialData vivid_sample_slab_7 = VividCreateSlabMaterialData(vivid_sample_resource_7);
    const float2 vivid_sample_uv_7 = vivid_v0001 * vivid_sample_slab_7.TextureTilingOffset.xy + vivid_sample_slab_7.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_7 = vivid_v0005 * vivid_sample_slab_7.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_7 = vivid_v0006 * vivid_sample_slab_7.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_7 = VividCreateSurfaceSampleContextGrad(vivid_sample_binding_7, vivid_sample_uv_7, vivid_sample_ddx_7, vivid_sample_ddy_7);
    const float4 vivid_v0007 = VividSampleBaseColorGrad(vivid_sample_binding_7, vivid_sample_context_7);
    const float4 vivid_v0008 = (vivid_v0003 * vivid_v0007);
    const float vivid_v0009 = vivid_v0008.w;
    const float vivid_v0010 = (vivid_v0000 * vivid_v0009);
    const float vivid_v0011 = saturate(vivid_v0010);

    VividMaterialCoverageEvaluation output;
    output.Coverage = vivid_v0011;
    output.AlphaClipThreshold = vivid_v0002;
    return output;
}

bool VividTryEvaluateAOTCoverageProgram(
    const VividMaterialRuntimeHeader runtimeHeader,
    const VividMaterialProgramData programData,
    const VividAOTCoverageContext context,
    out VividMaterialCoverageEvaluation output)
{
    output = (VividMaterialCoverageEvaluation) 0;
    switch (runtimeHeader.ProgramID)
    {
        case 0u:
        {
            const uint parameterLaneCount = 4u;
            const uint resourceCount = 1u;
            if (programData.ParameterLayoutID
                    != VIVIDMATERIALPARAMETERLAYOUTID_GENERIC_PARAMETER_LANES
                || programData.ResourceLayoutID
                    != VIVIDMATERIALRESOURCELAYOUTID_GENERIC_RESOURCE_RECORDS
                || runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            output = VividEvaluateAOTCoverage_73E31B25B101D550(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        case 1u:
        {
            const uint parameterLaneCount = 6u;
            const uint resourceCount = 2u;
            if (programData.ParameterLayoutID
                    != VIVIDMATERIALPARAMETERLAYOUTID_GENERIC_PARAMETER_LANES
                || programData.ResourceLayoutID
                    != VIVIDMATERIALRESOURCELAYOUTID_GENERIC_RESOURCE_RECORDS
                || runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            output = VividEvaluateAOTCoverage_1402C703249979FA(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        case 2u:
        {
            const uint parameterLaneCount = 6u;
            const uint resourceCount = 2u;
            if (programData.ParameterLayoutID
                    != VIVIDMATERIALPARAMETERLAYOUTID_GENERIC_PARAMETER_LANES
                || programData.ResourceLayoutID
                    != VIVIDMATERIALRESOURCELAYOUTID_GENERIC_RESOURCE_RECORDS
                || runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            output = VividEvaluateAOTCoverage_1402C703249979FA(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        case 3u:
        {
            const uint parameterLaneCount = 4u;
            const uint resourceCount = 1u;
            if (programData.ParameterLayoutID
                    != VIVIDMATERIALPARAMETERLAYOUTID_GENERIC_PARAMETER_LANES
                || programData.ResourceLayoutID
                    != VIVIDMATERIALRESOURCELAYOUTID_GENERIC_RESOURCE_RECORDS
                || runtimeHeader.ParameterAddress > _MaterialParameterDataCount
                || parameterLaneCount > _MaterialParameterDataCount - runtimeHeader.ParameterAddress
                || runtimeHeader.ResourceBindingAddress > _MaterialResourceDataCount
                || resourceCount > _MaterialResourceDataCount - runtimeHeader.ResourceBindingAddress)
                return false;
            output = VividEvaluateAOTCoverage_319E5482AA666435(
                runtimeHeader.ParameterAddress,
                runtimeHeader.ResourceBindingAddress,
                context);
            return true;
        }
        default:
            return false;
    }
}

#endif // VIVID_MATERIAL_COVERAGE_AOT_GENERATED_INCLUDED
