// <auto-generated by MaterialCoverageHlslGenerator>
// Generated from canonical Coverage Stage LIR; do not edit.
#ifndef VIVID_MATERIAL_COVERAGE_AOT_GENERATED_INCLUDED
#define VIVID_MATERIAL_COVERAGE_AOT_GENERATED_INCLUDED

#define VIVID_MATERIAL_COVERAGE_HLSL_BACKEND_VERSION 1u

#ifndef VIVID_MATERIAL_CATALOG_MANIFEST_INCLUDED
#define VIVID_MATERIAL_CATALOG_MANIFEST_INCLUDED
#define VIVID_MATERIAL_CATALOG_MANIFEST_VERSION 1u
#define VIVID_MATERIAL_CATALOG_MANIFEST_HASH_LO 0x2F95182Eu
#define VIVID_MATERIAL_CATALOG_MANIFEST_HASH_HI 0x6E6C3933u
#define VIVID_MATERIAL_CATALOG_PROGRAM_TABLE_LENGTH 3u
#elif VIVID_MATERIAL_CATALOG_MANIFEST_VERSION != 1u || VIVID_MATERIAL_CATALOG_MANIFEST_HASH_LO != 0x2F95182Eu || VIVID_MATERIAL_CATALOG_MANIFEST_HASH_HI != 0x6E6C3933u || VIVID_MATERIAL_CATALOG_PROGRAM_TABLE_LENGTH != 3u
#error Material Surface and Coverage dispatchers use different frozen catalog manifests.
#endif

struct VividAOTCoverageContext
{
    float2 UV0;
    float2 UV0Ddx;
    float2 UV0Ddy;
};

// Coverage AOT HLSL artifact v1, backend v1.
VividMaterialCoverageEvaluation VividEvaluateAOTCoverage_0ABA65136E54AD55(
    const VividMaterialData materialParameters,
    const VividSurfaceBindingData surfaceBinding0,
    const VividAOTCoverageContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float vivid_v0001 = materialParameters.AlphaClipThreshold;
    const float4 vivid_v0002 = materialParameters.AlbedoColor;
    const float2 vivid_v0004 = context.UV0Ddx;
    const float2 vivid_v0005 = context.UV0Ddy;
    const VividSlabMaterialData vivid_sample_slab_6 = VividCreateSlabMaterialData(materialParameters);
    const float2 vivid_sample_uv_6 = vivid_v0000 * vivid_sample_slab_6.TextureTilingOffset.xy + vivid_sample_slab_6.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_6 = vivid_v0004 * vivid_sample_slab_6.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_6 = vivid_v0005 * vivid_sample_slab_6.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_6 = VividCreateSurfaceSampleContextGrad(surfaceBinding0, vivid_sample_uv_6, vivid_sample_ddx_6, vivid_sample_ddy_6);
    const float4 vivid_v0006 = VividSampleBaseColorGrad(surfaceBinding0, vivid_sample_context_6);
    const float4 vivid_v0007 = (vivid_v0002 * vivid_v0006);
    const float vivid_v0008 = vivid_v0007.w;

    VividMaterialCoverageEvaluation output;
    output.Coverage = vivid_v0008;
    output.AlphaClipThreshold = vivid_v0001;
    return output;
}

// Coverage AOT HLSL artifact v1, backend v1.
VividMaterialCoverageEvaluation VividEvaluateAOTCoverage_BE64FF731EB867CE(
    const VividDualSlabMaterialData materialParameters,
    const VividSurfaceBindingData surfaceBinding0,
    const VividSurfaceBindingData surfaceBinding1,
    const VividAOTCoverageContext context)
{
    const float2 vivid_v0000 = context.UV0;
    const float vivid_v0001 = materialParameters.AlphaClipThreshold;
    const float4 vivid_v0002 = materialParameters.BaseAlbedoColor;
    const float2 vivid_v0004 = context.UV0Ddx;
    const float2 vivid_v0005 = context.UV0Ddy;
    const VividSlabMaterialData vivid_sample_slab_6 = VividGetBaseSlabMaterialData(materialParameters);
    const float2 vivid_sample_uv_6 = vivid_v0000 * vivid_sample_slab_6.TextureTilingOffset.xy + vivid_sample_slab_6.TextureTilingOffset.zw;
    const float2 vivid_sample_ddx_6 = vivid_v0004 * vivid_sample_slab_6.TextureTilingOffset.xy;
    const float2 vivid_sample_ddy_6 = vivid_v0005 * vivid_sample_slab_6.TextureTilingOffset.xy;
    const VividSurfaceSampleContext vivid_sample_context_6 = VividCreateSurfaceSampleContextGrad(surfaceBinding0, vivid_sample_uv_6, vivid_sample_ddx_6, vivid_sample_ddy_6);
    const float4 vivid_v0006 = VividSampleBaseColorGrad(surfaceBinding0, vivid_sample_context_6);
    const float4 vivid_v0007 = (vivid_v0002 * vivid_v0006);
    const float vivid_v0008 = vivid_v0007.w;

    VividMaterialCoverageEvaluation output;
    output.Coverage = vivid_v0008;
    output.AlphaClipThreshold = vivid_v0001;
    return output;
}

bool VividTryEvaluateAOTCoverageProgram(
    const VividMaterialRuntimeHeader runtimeHeader,
    const VividMaterialProgramData programData,
    const VividAOTCoverageContext context,
    out VividMaterialCoverageEvaluation output)
{
    output = (VividMaterialCoverageEvaluation) 0;
    switch (runtimeHeader.ProgramID)
    {
        case 0u:
        {
            if (programData.ParameterLayoutID
                    != VIVIDMATERIALPARAMETERLAYOUTID_LEGACY_MATERIAL_DATA
                || programData.ResourceLayoutID
                    != VIVIDMATERIALRESOURCELAYOUTID_LEGACY_SURFACE_BINDING
                || runtimeHeader.ParameterAddress >= _MaterialDataCount
                || runtimeHeader.ResourceBindingAddress >= _SurfaceBindingDataCount)
            {
                return false;
            }
            output = VividEvaluateAOTCoverage_0ABA65136E54AD55(
                PullMaterialData(runtimeHeader.ParameterAddress),
                PullSurfaceBindingData(runtimeHeader.ResourceBindingAddress),
                context);
            return true;
        }
        case 1u:
        {
            const uint bindingAddress = runtimeHeader.ResourceBindingAddress;
            if (programData.ParameterLayoutID
                    != VIVIDMATERIALPARAMETERLAYOUTID_DUAL_SLAB_MATERIAL_DATA
                || programData.ResourceLayoutID
                    != VIVIDMATERIALRESOURCELAYOUTID_DUAL_SURFACE_BINDING
                || runtimeHeader.ParameterAddress >= _DualSlabMaterialDataCount
                || bindingAddress >= _SurfaceBindingDataCount
                || _SurfaceBindingDataCount - bindingAddress < 2u)
            {
                return false;
            }
            output = VividEvaluateAOTCoverage_BE64FF731EB867CE(
                PullDualSlabMaterialData(runtimeHeader.ParameterAddress),
                PullSurfaceBindingData(bindingAddress),
                PullSurfaceBindingData(bindingAddress + 1u),
                context);
            return true;
        }
        case 2u:
        {
            const uint bindingAddress = runtimeHeader.ResourceBindingAddress;
            if (programData.ParameterLayoutID
                    != VIVIDMATERIALPARAMETERLAYOUTID_DUAL_SLAB_MATERIAL_DATA
                || programData.ResourceLayoutID
                    != VIVIDMATERIALRESOURCELAYOUTID_DUAL_SURFACE_BINDING
                || runtimeHeader.ParameterAddress >= _DualSlabMaterialDataCount
                || bindingAddress >= _SurfaceBindingDataCount
                || _SurfaceBindingDataCount - bindingAddress < 2u)
            {
                return false;
            }
            output = VividEvaluateAOTCoverage_BE64FF731EB867CE(
                PullDualSlabMaterialData(runtimeHeader.ParameterAddress),
                PullSurfaceBindingData(bindingAddress),
                PullSurfaceBindingData(bindingAddress + 1u),
                context);
            return true;
        }
        default:
            return false;
    }
}

#endif // VIVID_MATERIAL_COVERAGE_AOT_GENERATED_INCLUDED
