// Definitions
//--------------------------------------------------------------------------------------------------

// #pragma enable_d3d11_debug_symbols

// Kernel max num is SHADINGMODELS_MAX_MODELS_NUM
#pragma kernel DeferredClassifyTiles
#pragma kernel DeferredLighting


// #pragma multi_compile _ _DEFERRED_CLASSIFY_TILES _DEFERRED_LIGHTING
//
// #if defined(_DEFERRED_CLASSIFY_TILES)
// #define DEFERRED_CLASSIFY_TILES
// #endif
// #if defined(_DEFERRED_LIGHTING)
// #define DEFERRED_LIT
// #define DEFERRED_LIGHTING
// #endif

#pragma multi_compile _ _ADDITIONAL_LIGHT_SHADOWS
#pragma multi_compile _ _SHADOWS_SOFT
#pragma multi_compile _ _LIGHT_COOKIES
#pragma multi_compile _ _LIGHT_LAYERS
#pragma multi_compile _ _PEROBJECT_SCREEN_SPACE_SHADOW
#pragma multi_compile _ _SCREEN_SPACE_REFLECTION

// Always define keywords
#define _GPU_LIGHTS_CLUSTER

#pragma enable_d3d11_debug_symbols

//--------------------------------------------------------------------------------------------------
// Included headers
//--------------------------------------------------------------------------------------------------


#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Shaders/Utils/Deferred.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Extension/Material.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/ClusterLighting/GPULights.cs.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Extension/GPUCulledLights.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Input.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareDepthTexture.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Shadows.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/Filter/PreIntegratedFGD/Shader/PreIntegratedFGD.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/ClusterLighting/ShadingModels.cs.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Extension/TileClassify.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Extension/Environment/Environment.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Extension/AutoExposure.hlsl"

//--------------------------------------------------------------------------------------------------
// Inputs & outputs
//--------------------------------------------------------------------------------------------------


Texture2D<uint2> _StencilTexture;

RWBuffer<uint> g_DispatchIndirectBuffer;
RWStructuredBuffer<uint> g_TileList;

TEXTURE2D_X(_GBuffer0);
TEXTURE2D_X(_GBuffer1);
TEXTURE2D_X(_GBuffer2);
// Optional gbuffer, accroding to UnityGBuffer.hlsl defined
#ifdef GBUFFER_OPTIONAL_SLOT_1
TEXTURE2D_X(_GBuffer4);
#endif
#ifdef GBUFFER_OPTIONAL_SLOT_2
TEXTURE2D_X(_GBuffer5);
#endif
#ifdef GBUFFER_OPTIONAL_SLOT_3
TEXTURE2D_X(_GBuffer6);
#endif

// TEXTURE2D(_SSRLightingTexture);

RWTexture2D<float4> _LightingTexture;

int _ShadingModelIndex;
int _ShadingModelStencil;
int2 _TilesNum;

#include "LightingCommon.hlsl"
#include "PBRDeferredLit.hlsl"

//--------------------------------------------------------------------------------------------------
// Helpers
//--------------------------------------------------------------------------------------------------


int ShadingModelToIndex(uint shadingModel)
{
    if (shadingModel == SHADINGMODELS_LIT)
    {
        return 0;
    }
    // else if (shadingModel == SHADINGMODELS_SIMPLE_LIT)
    // {
    //     return 1;
    // }
    // else if (shadingModel == SHADINGMODELS_CHARACTER)
    // {
    //     return 2;
    // }

    return 0;
}

uint IndexToShadingModel(int index)
{
    if (index == 0)
    {
        return SHADINGMODELS_LIT;
    }
    // else if (index == 1)
    // {
    //     return SHADINGMODELS_SIMPLE_LIT;
    // }
    // else if (index == 2)
    // {
    //     return SHADINGMODELS_CHARACTER;
    // }

    return SHADINGMODELS_LIT;
}


void InitializeDispatchThreadIdFromTileList(uint groupId, uint2 gThreadId, out uint2 tileCoord, out uint2 dThreadId)
{
    uint encodedTileIndex = g_TileList[_ShadingModelIndex * _TilesNum.x * _TilesNum.y + (groupId / 4)];
    tileCoord = DecodeTileIndex(encodedTileIndex);
    dThreadId = tileCoord * DEFERRED_LIGHTING_TILE_SIZE
        + uint2(groupId & 1, (groupId >> 1) & 1) * DEFERRED_LIGHTING_GROUP_SIZE
        + gThreadId;
}


//--------------------------------------------------------------------------------------------------
// Implementation Classify Tiles
//--------------------------------------------------------------------------------------------------


groupshared uint gs_ShadingModelFlags[SHADINGMODELS_CUR_MODELS_NUM];

// Dispatch size is 16*16 (tile size), each group has 64 threads, each thread handle 4 piexels.
[numthreads(DEFERRED_LIGHTING_THREADS, 1, 1)]
void DeferredClassifyTiles(uint3 dispatchThreadId : SV_DispatchThreadID, uint groupIndex : SV_GroupIndex, uint3 groupID : SV_GroupID)
{
    uint2 tileID = groupID.xy;

    uint2 screenSize = _ScreenSize.xy;
    uint tilesNum;
    tilesNum = (screenSize.x + DEFERRED_LIGHTING_TILE_SIZE - 1) / DEFERRED_LIGHTING_TILE_SIZE;
    tilesNum *= (screenSize.y + DEFERRED_LIGHTING_TILE_SIZE - 1) / DEFERRED_LIGHTING_TILE_SIZE;


    uint2 coordBoundLL = DEFERRED_LIGHTING_TILE_SIZE * tileID;
    uint shadingModelFlags[SHADINGMODELS_CUR_MODELS_NUM] = (uint[SHADINGMODELS_CUR_MODELS_NUM])0;

    // Per tile Initialize
    if (groupIndex < SHADINGMODELS_CUR_MODELS_NUM)
    {
        gs_ShadingModelFlags[groupIndex] = 0;
    }
    GroupMemoryBarrierWithGroupSync();


    // Sampling stencil get shading models write to curr thread shadingModelFlags[]
    UNITY_UNROLL
    for (int i = 0; i < 4; i++)
    {
        int idx = i * DEFERRED_LIGHTING_THREADS + groupIndex;
        uint2 uCrd = min(uint2(coordBoundLL.x + (idx & 0xf), coordBoundLL.y + (idx >> 4)), uint2(screenSize.x - 1, screenSize.y - 1));

        uint stencilVal = GetStencilValue(LOAD_TEXTURE2D_X(_StencilTexture, uCrd));

        int flagIndex = ShadingModelToIndex(StencilToShadingModel(stencilVal));
        shadingModelFlags[flagIndex] |= (HasShadingModel(stencilVal) ? 1 : 0);
    }


    // Gather per tile shading models
    UNITY_UNROLL
    for (int j = 0; j < SHADINGMODELS_CUR_MODELS_NUM; j++)
    {
        if (shadingModelFlags[j] > 0)
        {
            InterlockedOr(gs_ShadingModelFlags[j], shadingModelFlags[j]);
        }
    }
    GroupMemoryBarrierWithGroupSync();


    // Write per tile data.
    if (groupIndex < SHADINGMODELS_CUR_MODELS_NUM)
    {
        if (gs_ShadingModelFlags[groupIndex] > 0)
        {
            uint tileOffset = 0;
            uint prevGroupCnt;
            // We are filling up an indirect argument buffer for DispatchIndirect.
            // The buffer contains {groupCntX, groupCntY, groupCntZ} = {groupCnt, 0, 0}.
            // Current thread contorls 4 pixels.
            InterlockedAdd(g_DispatchIndirectBuffer[groupIndex * 3], 4, prevGroupCnt);
            tileOffset = prevGroupCnt / 4; // 4x 8x8 groups per a 16x16 tile
            g_TileList[groupIndex * tilesNum + tileOffset] = EncodeTileIndex(tileID.xy);
        }
    }
}

#define SHADEROPTIONS_PRE_EXPOSITION 1
[numthreads(DEFERRED_LIGHTING_GROUP_SIZE, DEFERRED_LIGHTING_GROUP_SIZE, 1)]
void DeferredLighting(uint3 dispatchThreadId : SV_DispatchThreadID, uint2 groupThreadId : SV_GroupThreadID, uint groupId : SV_GroupID)
{
    uint2 coordSS;
    uint2 tileCoord;
    InitializeDispatchThreadIdFromTileList(groupId, groupThreadId, tileCoord, coordSS);

    // (0) Check valid first.
    // Reject the sky/background
    float depth = LoadSceneDepth(coordSS);
    if (depth == UNITY_RAW_FAR_CLIP_VALUE)
    {
        return;
    }

    PositionInputs posInput = GetPositionInput(coordSS.xy, _ScreenSize.zw, depth, UNITY_MATRIX_I_VP, UNITY_MATRIX_V, tileCoord);

    ShadingData shadingData = DecodeShadingDataFromGBuffer(posInput);
    DeferredLightingOutput lightOutput = Lightloop(posInput, shadingData);

    float3 diffuseLighting = lightOutput.diffuseLighting;
    float3 specularLighting = lightOutput.specularLighting;
    diffuseLighting *= GetCurrentExposureMultiplier();
    specularLighting *= GetCurrentExposureMultiplier();

    float3 emission = _LightingTexture[coordSS].rgb;
    _LightingTexture[coordSS] = float4(diffuseLighting + specularLighting + emission, 1.0);;
}
