#ifndef RTXGI_COORDINATE_SYSTEM
    #define RTXGI_COORDINATE_SYSTEM RTXGI_COORDINATE_SYSTEM_RIGHT
#endif

#ifndef RTXGI_DDGI_SHADER_REFLECTION
    #define RTXGI_DDGI_SHADER_REFLECTION 1
#endif

#ifndef RTXGI_DDGI_RESOURCE_MANAGEMENT
    #define RTXGI_DDGI_RESOURCE_MANAGEMENT 0
#endif

#ifndef RTXGI_DDGI_BINDLESS_RESOURCES
    #define RTXGI_DDGI_BINDLESS_RESOURCES 0
#endif

#ifndef RTXGI_DDGI_BLEND_SHARED_MEMORY
    #define RTXGI_DDGI_BLEND_SHARED_MEMORY 1
#endif

#ifndef RTXGI_DDGI_BLEND_RAYS_PER_PROBE
    #define RTXGI_DDGI_BLEND_RAYS_PER_PROBE 144
#endif

#ifndef RTXGI_DDGI_BLEND_SCROLL_SHARED_MEMORY
    #define RTXGI_DDGI_BLEND_SCROLL_SHARED_MEMORY 1
#endif

#ifndef RTXGI_DDGI_BLEND_RADIANCE
    #define RTXGI_DDGI_BLEND_RADIANCE 1
#endif

#ifndef RTXGI_DDGI_PROBE_NUM_TEXELS
    #define RTXGI_DDGI_PROBE_NUM_TEXELS 8
#endif

#ifndef RTXGI_DDGI_PROBE_NUM_INTERIOR_TEXELS
    #define RTXGI_DDGI_PROBE_NUM_INTERIOR_TEXELS (RTXGI_DDGI_PROBE_NUM_TEXELS - 2)
#endif

#ifndef RTXGI_DDGI_WAVE_LANE_COUNT
    #define RTXGI_DDGI_WAVE_LANE_COUNT WaveGetLaneCount()
#endif
