#define HAMMERSLEY_USE_CB
#pragma use_dxc

#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/GlobalSamplers.hlsl"
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/SphericalHarmonics.hlsl"
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Sampling/Hammersley.hlsl"
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Sampling/Sampling.hlsl"
#pragma only_renderers d3d11 playstation xboxone xboxseries vulkan metal switch switch2
#pragma kernel AmbientProbeConvolution

TEXTURECUBE(_AmbientProbeInputCubemap);
RWStructuredBuffer<float4> _AmbientProbeOutputBuffer;

float4 _SkyConvolutionTint;
float4 _SkyConvolutionParams;

#define _SkyExposure _SkyConvolutionParams.x
#define _SkyRotation _SkyConvolutionParams.y

#define SAMPLE_COUNT 256
#define SH_COEFF_COUNT 27

#if defined(PLATFORM_SUPPORTS_WAVE_INTRINSICS) && defined(PLATFORM_LANE_COUNT)
groupshared float outputSHCoeffsLDS[SH_COEFF_COUNT * SAMPLE_COUNT / PLATFORM_LANE_COUNT];
#else
groupshared float outputSHCoeffsLDS[SH_COEFF_COUNT * SAMPLE_COUNT / 2];
#endif

float3 RotateAroundYAxis(float3 directionWS, float rotationDegrees)
{
    float rotationRadians = radians(rotationDegrees);
    float s = 0.0;
    float c = 1.0;
    sincos(rotationRadians, s, c);

    return float3(
        c * directionWS.x - s * directionWS.z,
        directionWS.y,
        s * directionWS.x + c * directionWS.z);
}

[numthreads(SAMPLE_COUNT, 1, 1)]
void AmbientProbeConvolution(uint dispatchThreadId : SV_DispatchThreadID)
{
    uint sampleCount = SAMPLE_COUNT;

    float2 u = Hammersley2d(dispatchThreadId, sampleCount);
    float3 n = SampleSphereUniform(u.x, u.y);
    n = RotateAroundYAxis(n, _SkyRotation);

    float2 cubeSize;
    _AmbientProbeInputCubemap.GetDimensions(cubeSize.x, cubeSize.y);

    float invOmegaP = (6.0 * cubeSize.x * cubeSize.y) / FOUR_PI;
    float pdf = 1.0 / FOUR_PI;
    float omegaS = rcp(sampleCount) * rcp(pdf);
    float mipLevel = 0.5 * log2(omegaS * invOmegaP);

    float3 value = SAMPLE_TEXTURECUBE_LOD(_AmbientProbeInputCubemap, sampler_LinearClamp, n, mipLevel).rgb;
    value *= _SkyConvolutionTint.rgb * _SkyExposure;

    float outputSHCoeffs[SH_COEFF_COUNT];

    [unroll]
    for (int channel = 0; channel < 3; ++channel)
    {
        outputSHCoeffs[channel * 9 + 0] = value[channel];
        outputSHCoeffs[channel * 9 + 1] = n.y * value[channel];
        outputSHCoeffs[channel * 9 + 2] = n.z * value[channel];
        outputSHCoeffs[channel * 9 + 3] = n.x * value[channel];
        outputSHCoeffs[channel * 9 + 4] = n.x * n.y * value[channel];
        outputSHCoeffs[channel * 9 + 5] = n.y * n.z * value[channel];
        outputSHCoeffs[channel * 9 + 6] = (3.0 * n.z * n.z - 1.0) * value[channel];
        outputSHCoeffs[channel * 9 + 7] = n.x * n.z * value[channel];
        outputSHCoeffs[channel * 9 + 8] = (n.x * n.x - n.y * n.y) * value[channel];
    }

#if defined(PLATFORM_SUPPORTS_WAVE_INTRINSICS) && defined(PLATFORM_LANE_COUNT)
    [unroll]
    for (uint coeff = 0; coeff < SH_COEFF_COUNT; ++coeff)
    {
        outputSHCoeffs[coeff] = WaveActiveSum(outputSHCoeffs[coeff]);
    }

    uint laneCount = WaveGetLaneCount();
    if (dispatchThreadId % laneCount == 0)
    {
        [unroll]
        for (uint coeff = 0; coeff < SH_COEFF_COUNT; ++coeff)
        {
            uint offset = (dispatchThreadId / laneCount) * SH_COEFF_COUNT;
            outputSHCoeffsLDS[coeff + offset] = outputSHCoeffs[coeff];
        }
    }

    GroupMemoryBarrierWithGroupSync();

    [unroll]
    for (uint coeff = 0; coeff < SH_COEFF_COUNT; ++coeff)
    {
        outputSHCoeffs[coeff] = outputSHCoeffsLDS[coeff];
    }

    uint waveCount = sampleCount / laneCount;
    for (uint wave = 1; wave < waveCount; ++wave)
    {
        [unroll]
        for (uint coeff = 0; coeff < SH_COEFF_COUNT; ++coeff)
        {
            outputSHCoeffs[coeff] += outputSHCoeffsLDS[coeff + wave * SH_COEFF_COUNT];
        }
    }
#else
    for (uint reductionStep = 0; reductionStep < FastLog2(SAMPLE_COUNT); ++reductionStep)
    {
        if ((dispatchThreadId & ((2 << reductionStep) - 1)) == (1 << reductionStep))
        {
            uint index = dispatchThreadId >> (reductionStep + 1);
            [unroll]
            for (uint coeff = 0; coeff < SH_COEFF_COUNT; ++coeff)
            {
                outputSHCoeffsLDS[index * SH_COEFF_COUNT + coeff] = outputSHCoeffs[coeff];
            }
        }

        GroupMemoryBarrierWithGroupSync();

        if ((dispatchThreadId & ((2 << reductionStep) - 1)) == 0)
        {
            uint index = dispatchThreadId >> (reductionStep + 1);
            [unroll]
            for (uint coeff = 0; coeff < SH_COEFF_COUNT; ++coeff)
            {
                outputSHCoeffs[coeff] += outputSHCoeffsLDS[index * SH_COEFF_COUNT + coeff];
            }
        }

        GroupMemoryBarrierWithGroupSync();
    }
#endif

    if (dispatchThreadId != 0)
        return;

    float weight = FOUR_PI / sampleCount;

    [unroll]
    for (uint coeff = 0; coeff < SH_COEFF_COUNT; ++coeff)
    {
        outputSHCoeffs[coeff] *= kSHBasisCoef[coeff % 9] * weight;
        outputSHCoeffs[coeff] *= kClampedCosineCoefs[coeff % 9] * kSHBasisCoef[coeff % 9];
    }

    PackSH(_AmbientProbeOutputBuffer, outputSHCoeffs);
}
