#pragma kernel CS

#pragma use_dxc

#include "Packages/com.vivid.render-pipelines/Shaders/Core/Public/GPUDriven/VividGPUDrivenCommon.hlsl"

StructuredBuffer<VividGPUCullingContext> _CullingContexts;
StructuredBuffer<uint> _VisibleMeshletRenderRequestCounter;
RWStructuredBuffer<uint> _VisibleRendererListMeshletCounts;
RWStructuredBuffer<uint> _GPUMeshletCullingIndirectDispatchArgs;
RWByteAddressBuffer _VisibleMeshletIndirectDrawArgs;
uint _CullingContextCount;

[numthreads(1, 1, 1)]
void CS(const uint3 dispatchThreadID : SV_DispatchThreadID)
{
    const uint cullingContextCount = max(_CullingContextCount, 1u);
    const uint cullingContextIndex = dispatchThreadID.x;
    if (cullingContextIndex >= cullingContextCount)
    {
        return;
    }

    if (cullingContextIndex == 0u)
    {
        _GPUMeshletCullingIndirectDispatchArgs[1] = cullingContextCount;
        _GPUMeshletCullingIndirectDispatchArgs[2] = 1u;
    }

    const uint visibleMeshletRequestCount = _VisibleMeshletRenderRequestCounter[cullingContextIndex];
    const uint threadGroupCount = (visibleMeshletRequestCount + 31u) / 32u;
    InterlockedMax(_GPUMeshletCullingIndirectDispatchArgs[0], threadGroupCount);

    const VividGPUCullingContext cullingContext = _CullingContexts[cullingContextIndex];
    const uint rendererListBaseIndex = cullingContextIndex * VIVIDRENDERERLISTID_COUNT;
    uint startInstance = cullingContext.BaseStartInstance;

    [unroll]
    for (uint rendererListIndex = 0u; rendererListIndex < VIVIDRENDERERLISTID_COUNT; ++rendererListIndex)
    {
        const uint rendererListCountIndex = rendererListBaseIndex + rendererListIndex;
        const uint maxInstanceCount = _VisibleRendererListMeshletCounts[rendererListCountIndex];
        const uint drawArgsAddress = GetIndirectDrawArgsByteAddress(rendererListCountIndex);
        _VisibleMeshletIndirectDrawArgs.Store4(
            drawArgsAddress,
            uint4(
                VIVID_MAX_MESHLET_INDICES,
                0u,
                0u,
                startInstance
            )
        );
        _VisibleRendererListMeshletCounts[rendererListCountIndex] = 0u;

        startInstance += maxInstanceCount;
    }
}
