#pragma kernel CS

#pragma use_dxc

#include "Packages/com.vivid.render-pipelines/Shaders/Core/Public/GPUDriven/VividGPUDrivenCommon.hlsl"

StructuredBuffer<uint> _VisibleMeshletRenderRequestCounter;
RWStructuredBuffer<uint> _VisibleRendererListMeshletCounts;
RWStructuredBuffer<uint> _GPUMeshletCullingIndirectDispatchArgs;
RWByteAddressBuffer _VisibleMeshletIndirectDrawArgs;

[numthreads(1, 1, 1)]
void CS(const uint3 dispatchThreadID : SV_DispatchThreadID)
{
    if (dispatchThreadID.x != 0u)
    {
        return;
    }

    const uint visibleMeshletRequestCount = _VisibleMeshletRenderRequestCounter[0];
    _GPUMeshletCullingIndirectDispatchArgs[0] = (visibleMeshletRequestCount + 31u) / 32u;
    _GPUMeshletCullingIndirectDispatchArgs[1] = 1u;
    _GPUMeshletCullingIndirectDispatchArgs[2] = 1u;

    uint startInstance = 0u;

    [unroll]
    for (uint rendererListIndex = 0u; rendererListIndex < VIVIDRENDERERLISTID_COUNT; ++rendererListIndex)
    {
        const uint maxInstanceCount = _VisibleRendererListMeshletCounts[rendererListIndex];
        const uint drawArgsAddress = GetIndirectDrawArgsByteAddress(rendererListIndex);
        _VisibleMeshletIndirectDrawArgs.Store4(
            drawArgsAddress,
            uint4(
                VIVID_MAX_MESHLET_INDICES,
                0u,
                0u,
                startInstance
            )
        );
        _VisibleRendererListMeshletCounts[rendererListIndex] = 0u;

        startInstance += maxInstanceCount;
    }
}
