#pragma kernel CS

#pragma use_dxc

#include "Packages/com.af8a2a.vividrp/Shaders/Core/Public/GPUDriven/VividGPUDrivenCommon.hlsl"

#define THREAD_GROUP_SIZE 32
#define MAX_LODNODES_PER_THREAD_GROUP 32u

StructuredBuffer<VividGPUCullingContext> _CullingContexts;

RWStructuredBuffer<VividMeshletListBuildJob> _MeshletListBuildJobs;
RWStructuredBuffer<uint> _MeshletListBuildJobCounter;
RWStructuredBuffer<uint> _MeshletListBuildIndirectArgs;

[numthreads(THREAD_GROUP_SIZE, 1, 1)]
void CS(const uint3 dispatchThreadID : SV_DispatchThreadID)
{
    const uint instanceID = dispatchThreadID.x;
    if (instanceID >= _InstanceDataCount)
    {
        return;
    }

    const VividInstanceData instanceData = PullInstanceData(instanceID);
    const VividGPUCullingContext cullingContext = _CullingContexts[0];

    if ((instanceData.Flags & VIVIDINSTANCEFLAGS_DISABLED) != 0u ||
        (instanceData.PassMask & (uint) cullingContext.PassMask) == 0u)
    {
        return;
    }

    const float4 boundingSphereWS = ComputeInstanceBoundingSphereWS(instanceData);
    if (!FrustumVsSphere(cullingContext, boundingSphereWS) ||
        !LightSphereCulling(cullingContext, boundingSphereWS))
    {
        return;
    }

    const uint totalMeshLODCount = instanceData.TotalMeshLODCount;
    if (totalMeshLODCount == 0u)
    {
        return;
    }

    const uint jobCount = (totalMeshLODCount + MAX_LODNODES_PER_THREAD_GROUP - 1u) / MAX_LODNODES_PER_THREAD_GROUP;

    uint jobWriteOffset;
    InterlockedAdd(_MeshletListBuildJobCounter[0], jobCount, jobWriteOffset);
    InterlockedAdd(_MeshletListBuildIndirectArgs[0], jobCount);

    [loop]
    for (uint jobIndex = 0u; jobIndex < jobCount; ++jobIndex)
    {
        const uint offset = jobIndex * MAX_LODNODES_PER_THREAD_GROUP;
        const uint remainingNodeCount = totalMeshLODCount - offset;

        VividMeshletListBuildJob job;
        job.InstanceID = instanceID;
        job.MeshLODNodeOffset = offset;
        job.MeshLODNodeCount = min(remainingNodeCount, MAX_LODNODES_PER_THREAD_GROUP);
        job.Padding0 = 0u;
        _MeshletListBuildJobs[jobWriteOffset + jobIndex] = job;
    }
}
