
#pragma only_renderers d3d11 playstation xboxone xboxseries vulkan metal switch
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/TextureXR.hlsl"

CBUFFER_START (UnityCBuffer)
  uint2 _RectOffset;
CBUFFER_END

RW_TEXTURE2D(float, _Result1);
TEXTURE2D(_Source4);

#pragma kernel KSampleCopy4_1_x_8   KERNEL_NAME41=KSampleCopy4_1_x_8  KERNEL_SIZE=8
#pragma kernel KSampleCopy4_1_x_1   KERNEL_NAME41=KSampleCopy4_1_x_1  KERNEL_SIZE=1
[numthreads(KERNEL_SIZE, KERNEL_SIZE, 1)]
void KERNEL_NAME41(uint3 dispatchThreadId : SV_DispatchThreadID)
{

    uint2 positionSS = _RectOffset + dispatchThreadId.xy;
    _Result1[(positionSS)] = LOAD_TEXTURE2D_X(_Source4, positionSS).x;
}
