#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#pragma kernel Divergence

//-------------------------------------------------------------------------------------------------
//Parameter
//-------------------------------------------------------------------------------------------------

Texture2D _VelocityTexture;

RWTexture2D<float> _DivergenceTextureRW;

float _SimulationResolution;

[numthreads(8, 8, 1)]
void Divergence(uint3 dispatchThreadId : SV_DispatchThreadID)
{
    uint2 id = dispatchThreadId.xy;
    float invResolution = rcp(_SimulationResolution);
    float2 uv = (id + 0.5) * invResolution;

    float2 uvL = uv - float2(1, 0) * invResolution;
    float2 uvR = uv + float2(1, 0) * invResolution;
    float2 uvT = uv + float2(0, 1) * invResolution;
    float2 uvB = uv - float2(0, 1) * invResolution;

    float2 L = _VelocityTexture.SampleLevel(sampler_LinearClamp, uvL, 0).xy;
    float2 R = _VelocityTexture.SampleLevel(sampler_LinearClamp, uvR, 0).xy;
    float2 T = _VelocityTexture.SampleLevel(sampler_LinearClamp, uvT, 0).xy;
    float2 B = _VelocityTexture.SampleLevel(sampler_LinearClamp, uvB, 0).xy;

    float2 C = _VelocityTexture.SampleLevel(sampler_LinearClamp, uv, 0).xy;
    if(uvL.x <= 0) L.x = -C.x;
    if(uvR.x >= 1) R.x = -C.x;
    if(uvT.y >= 1) T.y = -C.y;
    if(uvB.y <= 0) B.y = -C.y;

    float dx_Half =  0.5f;
    _DivergenceTextureRW[id] = dx_Half * (R.x - L.x + T.y - B.y);
}
