#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#pragma kernel Diffusion

//-------------------------------------------------------------------------------------------------
//Parameter
//-------------------------------------------------------------------------------------------------

Texture2D _VelocityTexture;

RWTexture2D<float2> _DiffusionTextureRW;

float4 _DiffusionParameter;

#define _Viscosity _DiffusionParameter.x
#define _Alpha _DiffusionParameter.y
#define _Beta _DiffusionParameter.z
#define _SimulationResolution _DiffusionParameter.w

#define _DeltaTime unity_DeltaTime.x

[numthreads(8, 8, 1)]
void Diffusion(uint3 dispatchThreadId : SV_DispatchThreadID, uint threadID : SV_GroupIndex)
{
    uint2 id = dispatchThreadId.xy;
    float invResolution = rcp(_SimulationResolution);
    float2 uv = (id + 0.5) * invResolution;

    float2 uvL = uv - float2(1, 0) * invResolution;
    float2 uvR = uv + float2(1, 0) * invResolution;
    float2 uvT = uv + float2(0, 1) * invResolution;
    float2 uvB = uv - float2(0, 1) * invResolution;

    float2 L = _VelocityTexture.SampleLevel(sampler_LinearClamp, uvL, 0).xy;
    float2 R = _VelocityTexture.SampleLevel(sampler_LinearClamp, uvR, 0).xy;
    float2 T = _VelocityTexture.SampleLevel(sampler_LinearClamp, uvT, 0).xy;
    float2 B = _VelocityTexture.SampleLevel(sampler_LinearClamp, uvB, 0).xy;

    float2 bC = _VelocityTexture.SampleLevel(sampler_LinearClamp, uv, 0).xy;

    _DiffusionTextureRW[id] = float4((L + R + T + B + _Alpha * bC) / _Beta, 0, 1);
}
