#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#pragma kernel Advection

//-------------------------------------------------------------------------------------------------
//Parameter
//-------------------------------------------------------------------------------------------------

Texture2D _VelocityTexture;


//transfer velocity
RWTexture2D<float2> _VelocityTextureRW;

//other material Advect
RWTexture2D<float4> _Material;

float _AdvectSpeed;
float _SimulationResolution; 
#define _DeltaTime unity_DeltaTime.z

[numthreads(8, 8, 1)]
void Advection(uint3 dispatchThreadId : SV_DispatchThreadID)
{
    uint2 id = dispatchThreadId.xy;
    float invResolution = rcp(_SimulationResolution);
    float2 uv = id * invResolution + 0.5 * invResolution;

    float2 velocity = _VelocityTexture.SampleLevel(sampler_LinearClamp, uv, 0).xy;
    float2 newUV = uv - velocity * _DeltaTime * _AdvectSpeed * 0.2;
    _VelocityTextureRW[id] = _VelocityTexture.SampleLevel(sampler_LinearClamp, newUV, 0);
}
