#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#pragma kernel ApplyForce

//-------------------------------------------------------------------------------------------------
//Parameter
//-------------------------------------------------------------------------------------------------

Texture2D _VelocityTexture;

RWTexture2D<float2> _VelocityTextureRW;


struct InteractorData
{
    float2 PositionOS;
    float2 Force;
    float Radius;
};

int _InteractorCount;
float _SimulationResolution;
StructuredBuffer<InteractorData> _InteractorData;

#define _DeltaTime unity_DeltaTime.z


[numthreads(8, 8, 1)]
void ApplyForce(uint3 dispatchThreadId : SV_DispatchThreadID, uint threadID : SV_GroupIndex)
{
    uint2 id = dispatchThreadId.xy;
    float invResolution = rcp(_SimulationResolution);
    float2 uv = id * invResolution + 0.5 * invResolution;
    float2 velocity = _VelocityTexture.SampleLevel(sampler_LinearClamp, uv, 0);
    for (int i = 0; i < _InteractorCount; i++)
    {
        InteractorData data = _InteractorData[i];
        float2 dir = data.PositionOS - uv;
        velocity += data.Force * exp(-dot(dir, dir) / (data.Radius * 0.001)) * _DeltaTime * 200;
        
    }
    _VelocityTextureRW[id] = velocity;
}
