#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#pragma kernel Gradient
#pragma enable_d3d11_debug_symbols

//-------------------------------------------------------------------------------------------------
//Parameter
//-------------------------------------------------------------------------------------------------

Texture2D _PressureTexture;
Texture2D _VelocityTexture;

RWTexture2D<float2> _VelocityTextureRW;

float _SimulationResolution;

[numthreads(8, 8, 1)]
void Gradient(uint3 dispatchThreadId : SV_DispatchThreadID)
{
    uint2 id = dispatchThreadId.xy;
    float invResolution = rcp(_SimulationResolution);
    float2 uv = id * invResolution + 0.5 * invResolution;

    float2 uvL = uv - float2(1, 0) * invResolution;
    float2 uvR = uv + float2(1, 0) * invResolution;
    float2 uvT = uv + float2(0, 1) * invResolution;
    float2 uvB = uv - float2(0, 1) * invResolution;

    float L = _PressureTexture.SampleLevel(sampler_LinearClamp, uvL, 0).x;
    float R = _PressureTexture.SampleLevel(sampler_LinearClamp, uvR, 0).x;
    float T = _PressureTexture.SampleLevel(sampler_LinearClamp, uvT, 0).x;
    float B = _PressureTexture.SampleLevel(sampler_LinearClamp, uvB, 0).x;

    float2 C = _VelocityTexture.SampleLevel(sampler_LinearClamp, uv, 0).xy;
    float dx_Half = 0.5f;

    C -= dx_Half * float2(R - L, T - B);

    _VelocityTextureRW[id] = C;
}
