#pragma kernel ClearAtomic

#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"

#pragma only_renderers d3d11 playstation xboxone xboxseries vulkan metal switch switch2

RWStructuredBuffer<uint> g_LayeredSingleIdxBuffer : register(u2);

[numthreads(1, 1, 1)]
void ClearAtomic(uint threadID : SV_GroupIndex, uint3 groupID : SV_GroupID)
{
    g_LayeredSingleIdxBuffer[0] = 0;
}
