#ifndef VIVIDRP_LIGHTING_SHADERCONFIG_CS_HLSL
#define VIVIDRP_LIGHTING_SHADERCONFIG_CS_HLSL

#define SHADEROPTIONS_LIGHT_CLUSTER_MAX_CELL_ELEMENT_COUNT (24)
#define MAX_NR_BIG_TILE_LIGHTS_PLUS_ONE (512)
#define LIGHT_LIST_MAX_COARSE_ENTRIES (64)
#define LIGHT_CLUSTER_MAX_COARSE_ENTRIES (128)
#define LIGHT_DWORD_PER_FPTL_TILE (32)
#define LIGHT_CLUSTER_PACKING_COUNT_BITS (6)
#define LIGHT_CLUSTER_PACKING_COUNT_MASK (63)
#define LIGHT_CLUSTER_PACKING_OFFSET_BITS (26)
#define LIGHT_CLUSTER_PACKING_OFFSET_MASK (67108863)

#endif
