#pragma kernel RTAOApplyIntensity

#pragma only_renderers d3d11 xboxseries ps5

// HDRP generic includes
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl"

#pragma only_renderers d3d11 xboxseries ps5
// #pragma enable_d3d11_debug_symbols

// Tile size of this compute
#define RAYTRACING_AMBIENT_OCCLUSION_TILE_SIZE 8

float intensity;
RW_TEXTURE2D(float, _AmbientOcclusionTextureRW);
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/Filter/Denoiser/NRD/NRD.hlsl"
[numthreads(RAYTRACING_AMBIENT_OCCLUSION_TILE_SIZE, RAYTRACING_AMBIENT_OCCLUSION_TILE_SIZE, 1)]
void RTAOApplyIntensity(uint3 dispatchThreadId : SV_DispatchThreadID, uint2 groupThreadId : SV_GroupThreadID, uint2 groupId : SV_GroupID)
{

    // Compute the pixel position to process
    uint2 currentCoord = groupId * RAYTRACING_AMBIENT_OCCLUSION_TILE_SIZE + groupThreadId;

    // Grab the AO value without the intensity
    float value = _AmbientOcclusionTextureRW[(currentCoord)];
    float ao=
    _AmbientOcclusionTextureRW[(currentCoord)] = PositivePow(value, intensity);//1.0 - PositivePow(value, intensity);
}
