#include "UnityRayQuery.cginc"
#pragma kernel RTAO

#define SHADER_STAGE_RAY_TRACING 1
#pragma require inlineraytracing

#pragma only_renderers d3d11 xboxseries ps5

#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/Raytracing/Shaders/RayTracingCommon.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/Raytracing/Shaders/RaytracingIntersection.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/Raytracing/RayTracingFallbackHierarchy.cs.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/Raytracing/Shaders/RaytracingSampling.hlsl"
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Sampling/Sampling.hlsl"

Texture2D<float> SceneDepth;
Texture2D<float> SceneNormal;


float radius;
float intensity;
int sampleCount;
int frameIndex;
RWTexture2D<float> AmbientOcclusionTexture;

RaytracingAccelerationStructure _AccelerationStructure;



float3 cosineSampleHemisphere(float2 u) {
    float phi = 2 * PI * u.x;
    float cosTheta = sqrt(u.y);
    float sinTheta = sqrt(1 - cosTheta * cosTheta);
    return float3(cos(phi) * sinTheta, sin(phi) * sinTheta, cosTheta);
}

float3x3 GetTangentBasis( float3 TangentZ )
{
    const float Sign = TangentZ.z >= 0 ? 1 : -1;
    const float a = -rcp( Sign + TangentZ.z );
    const float b = TangentZ.x * TangentZ.y * a;

    float3 TangentX = {1 + Sign * a * pow(TangentZ.x, 2), Sign * b, -Sign * TangentZ.x};
    float3 TangentY = {b, Sign + a * pow(TangentZ.y, 2), -TangentZ.y};

    return float3x3( TangentX, TangentY, TangentZ );
}

[numthreads(8, 8, 1)]
void RTAO(const uint2 coordSS : SV_DispatchThreadID)
{
    // Load depth
    float rawDepth = SceneDepth[coordSS];
    // Background, early out.
    if (rawDepth == UNITY_RAW_FAR_CLIP_VALUE)
        return;


    PositionInputs posInput = GetPositionInput(coordSS, _ScreenSize.zw, rawDepth, UNITY_MATRIX_I_VP, UNITY_MATRIX_V, 0);

    float3 normalWS = SceneNormal[coordSS];

    // Evaluate the ray bias
    float rayBias = EvaluateRayTracingBias(posInput.positionWS);


    // r: scene shadow, g: character selfshadow
    float block = 0;


    UnityRayQuery<RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH> shadowQuery;
    RayDesc aoRay;

    // Ray
    for (int i = 0; i < sampleCount; i++)
    {
        float2 noiseValue;
        noiseValue.x = GetBNDSequenceSample(coordSS, frameIndex, 0);
        noiseValue.y = GetBNDSequenceSample(coordSS, frameIndex, 1);
        float3 sampleDir = SampleHemisphereCosine(noiseValue.x, noiseValue.y, normalWS);


        float3 rayDirWS = mul(sampleDir, GetTangentBasis(normalWS));

        
        aoRay.Origin = posInput.positionWS + normalWS * 0.15;
        aoRay.Direction = rayDirWS;
        aoRay.TMin = 0.001;
        aoRay.TMax = radius;
        
        shadowQuery.TraceRayInline(_AccelerationStructure, RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH, 0xff, aoRay);
        shadowQuery.Proceed();
        
        block += shadowQuery.CommittedStatus() == COMMITTED_TRIANGLE_HIT;
    }
    block /= (float)sampleCount;

    // float2 noiseValue;
    // noiseValue.x = GetBNDSequenceSample(coordSS, frameIndex, 0);
    // noiseValue.y = GetBNDSequenceSample(coordSS, frameIndex, 1);
    // float3 sampleDir = SampleHemisphereCosine(noiseValue.x, noiseValue.y, normalWS);


    AmbientOcclusionTexture[coordSS] = 1.0 - PositivePow(block, intensity);
}
