#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"

#pragma only_renderers d3d11 playstation xboxone xboxseries vulkan metal switch

#pragma kernel KMain
#pragma multi_compile _ ENABLE_ALPHA

#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Extension/PostProcess/PostProcessDefines.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Extension/AutoExposure.hlsl"
TEXTURE2D(_InputTexture);
RW_TEXTURE2D(CTYPE, _OutputTexture);




[numthreads(8,8,1)]
void KMain(uint3 dispatchThreadId : SV_DispatchThreadID)
{
    float exposure = GetCurrentExposureMultiplier();
    CTYPE color = LOAD_TEXTURE2D(_InputTexture, dispatchThreadId.xy).CTYPE_SWIZZLE;
    color.xyz *= exposure;
    _OutputTexture[dispatchThreadId.xy] = color;
}
