/*
Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.

NVIDIA CORPORATION and its licensors retain all intellectual property
and proprietary rights in and to this software, related documentation
and any modifications thereto. Any use, reproduction, disclosure or
distribution of this software and related documentation without an express
license agreement from NVIDIA CORPORATION is strictly prohibited.
*/

#pragma only_renderers d3d11 xboxseries ps5
#pragma use_dxc

#define NRD_VIVIDRP
#define gNearestClamp gPointClamp



#pragma multi_compile _ _NRD_OCCLUSION



#if defined(_NRD_OCCLUSION)
#define NRD_SIGNAL DIFF
#define NRD_DIFF 1
#define NRD_MODE OCCLUSION
#else
#define NRD_SIGNAL DIFF

#endif
#define NRD_INTERNAL 1


#pragma multi_compile _ _MODE_5X5

#ifdef _MODE_5X5
#define MODE_5X5 1
#endif



#include "../NRD.hlsl"
#include "../ml.hlsl"


#include "Private/REBLUR_Config.hlsl"

#include "Private/REBLUR_HistoryFix.resources.hlsl"

#include "../Common.hlsl"
#include "Private/REBLUR_Common.hlsl"
#include "Private/REBLUR_HistoryFix.hlsl"


#pragma kernel main


