// <auto-generated by VividPerObjectLayoutGenerator>
// Generated from VividPerObjectLayout types in Player assemblies; do not edit.
#ifndef VIVID_PER_OBJECT_LAYOUTS_GENERATED_INCLUDED
#define VIVID_PER_OBJECT_LAYOUTS_GENERATED_INCLUDED

#include "Packages/com.vivid.render-pipelines/Shaders/Core/Public/PerObjectBuffer.hlsl"

// VividRP.Runtime.Examples.VividPerObjectColorExampleLayout
#if defined(VIVID_PER_OBJECT_LAYOUT_PerObjectColorExample)
#define VIVID_PER_OBJECT_PerObjectColorExample_SIGNATURE 0x6C2F3B17u
#define VIVID_PER_OBJECT_PerObjectColorExample_STRIDE 32u
static VividPerObjectContext VividPerObjectContext_PerObjectColorExample;
#define VIVID_SETUP_PER_OBJECT_PerObjectColorExample() \
    VividPerObjectContext_PerObjectColorExample = VividPerObjectCreateContext(VIVID_PER_OBJECT_PerObjectColorExample_SIGNATURE)

float4 VividPerObject_PerObjectColorExample_Get__PerObjectColor()
{
    return VividPerObjectLoadFloat4(VividPerObjectContext_PerObjectColorExample, 4u, float4(asfloat(0x3F800000u), asfloat(0x3F800000u), asfloat(0x3F800000u), asfloat(0x3F800000u)));
}

#if !defined(VIVID_PER_OBJECT_NO_PROPERTY_ALIASES)
    #if defined(VIVID_PER_OBJECT_LAYOUT_ALIASES_SELECTED)
        #error Only one VIVID_PER_OBJECT_LAYOUT_<Identifier> may enable property aliases per shader program.
    #endif
    #define VIVID_PER_OBJECT_LAYOUT_ALIASES_SELECTED 1
    #define _PerObjectColor VividPerObject_PerObjectColorExample_Get__PerObjectColor()
#endif
#endif

#endif
