// <auto-generated by VividPerObjectLayoutGenerator>
// Generated from VividPerObjectLayout types in Player assemblies; do not edit.
#ifndef VIVID_PER_OBJECT_LAYOUTS_GENERATED_INCLUDED
#define VIVID_PER_OBJECT_LAYOUTS_GENERATED_INCLUDED

#include "Packages/com.vivid.render-pipelines/Shaders/Core/Public/PerObjectBuffer.hlsl"

// No concrete VividPerObjectLayout types were discovered.
#endif
