namespace UnityEngine.Rendering.Universal
{
    [VolumeRequiresRendererFeatures(typeof(RaytracingCoreFeature))]
    partial class AmbientOcclusion 
    {
        
        
        public MinFloatParameter rayLength = new MinFloatParameter(1.0f, 0.01f);

        
        public IntParameter samplesPerPixel = new ClampedIntParameter(1, 1, 16);

        
        /// <summary>
        /// When enabled, ambient occlusion generated by moving objects will not be accumulated, generating less ghosting but introducing additional noise.
        /// </summary>
        [AdditionalProperty]
        public BoolParameter occluderMotionRejection = new BoolParameter(true);

        /// <summary>
        /// When enabled, ambient occlusion generated on moving objects will not be accumulated, generating less ghosting but introducing additional noise.
        /// </summary>
        [AdditionalProperty] public BoolParameter receiverMotionRejection = new BoolParameter(true);

        
        // Ray tracing parameters
        /// <summary>
        /// Defines the layers that ray traced ambient occlusion should include.
        /// </summary>
        [AdditionalProperty] public LayerMaskParameter layerMask = new LayerMaskParameter(-1);

        
        
        public FloatParameter denoiseRadius = new ClampedFloatParameter(0f, 0.01f, 1f);

        
        //experiment option
        [AdditionalProperty]
        public BoolParameter rayQuery = new BoolParameter(false);
        [AdditionalProperty]
        public BoolParameter shaderExecutionReordering = new BoolParameter(false);

    }
}