namespace UnityEngine.Rendering.Universal
{
    [VolumeRequiresRendererFeatures(typeof(RaytracingCoreFeature), typeof(RaytracingAmbientOcclusionFeature))]
    public class RaytracingAmbientOcclusion : VolumeComponent
    {
        
        public BoolParameter enabled = new BoolParameter(false);

        
        
        public MinFloatParameter rayLength = new MinFloatParameter(1.0f, 0.01f);

        
        public IntParameter samplesPerPixel = new ClampedIntParameter(1, 1, 16);

        
        /// <summary>
        /// Controls the strength of the ambient occlusion effect. Increase this value to produce darker areas.
        /// </summary>
        public ClampedFloatParameter intensity = new ClampedFloatParameter(0f, 0f, 4f);

        /// <summary>
        /// Controls how much the ambient occlusion affects direct lighting.
        /// </summary>

        public FloatParameter directLightingStrength = new ClampedFloatParameter(0f, 0, 1);
        
        

        
        /// <summary>
        /// When enabled, ambient occlusion generated by moving objects will not be accumulated, generating less ghosting but introducing additional noise.
        /// </summary>
        [Header("Denoiser")] 
        [AdditionalProperty]
        public BoolParameter occluderMotionRejection = new BoolParameter(true);

        /// <summary>
        /// When enabled, ambient occlusion generated on moving objects will not be accumulated, generating less ghosting but introducing additional noise.
        /// </summary>
        [AdditionalProperty] public BoolParameter receiverMotionRejection = new BoolParameter(true);

        
        
        public FloatParameter denoiseRadius = new ClampedFloatParameter(0f, 0.01f, 1f);

        
        
        [Header("Experiment")]
        public BoolParameter rayQuery = new BoolParameter(false);
        
        public BoolParameter shaderExecutionReordering = new BoolParameter(false);


        public bool IsActive() => enabled.value;
    }
}