#pragma use_dxc
#pragma kernel CS
#pragma multi_compile_local _ VIVID_TSR_WAVE_OPS
#pragma multi_compile _ UNITY_DEVICE_SUPPORTS_NATIVE_16BIT

#include "Packages/com.vivid.render-pipelines/Shaders/Core/Private/TSR/TSRCommon.hlsl"

Texture2D<float4> _HistoryColor;
RWTexture2D<float4> _ResolvedOutput;

float4 _OutputSize;

[numthreads(8, 8, 1)]
void CS(uint3 dispatchThreadId : SV_DispatchThreadID)
{
    int2 outputSize = int2(_OutputSize.xy);
    int2 pixelCoord = int2(dispatchThreadId.xy);
    if (any(pixelCoord >= outputSize))
        return;

    _ResolvedOutput[pixelCoord] = _HistoryColor[pixelCoord];
}
