#include "UnityRayQuery.cginc"
#pragma kernel main

#define SHADER_STAGE_RAY_TRACING 1
#pragma require inlineraytracing

#pragma only_renderers d3d11 xboxseries ps5
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#include "Packages/com.unity.render-pipelines.core/Runtime/Sampling/Common.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/SubSystem/RayTracingSystem/Shaders/ShaderVariablesRaytracing.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/SubSystem/RayTracingSystem/Shaders/RayTracingCommon.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/SubSystem/RayTracingSystem/Shaders/RaytracingIntersection.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/SubSystem/RayTracingSystem/RayTracingFallbackHierarchy.cs.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/SubSystem/RayTracingSystem/Shaders/RaytracingSampling.hlsl"
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Sampling/Sampling.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/GBufferCommon.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Extension/LightGrid/ClusterLight.hlsl"

#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/Filter/Denoiser/NRD/NRD.hlsl"
#include "Packages/com.unity.render-pipelines.universal/Runtime/Extension/Filter/Denoiser/NRD/ml.hlsl"


#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/UnityGBuffer.hlsl"

Texture2D<float>  _SceneDepth;
Texture2D<float4> _SceneNormal;


int gFrameIndex;
float gTanSunAngularRadius;
float2 gJitter;

RWTexture2D<float> _UnfilterShadowTexture;

RaytracingAccelerationStructure _AccelerationStructure;


void GetBasis(float3 N, out float3 T, out float3 B)
{
    float sz = sign(N.z);
    float a = 1.0f / (sz + N.z);
    float ya = N.y * a;
    float b = N.x * ya;
    float c = N.x * sz;

    T = float3(c * N.x * a - 1.0f, sz * b, c);
    B = float3(b, N.y * ya - sz, N.y);
}


float2 GetConeAngleFromAngularRadius( float mip, float tanConeAngle )
{
    // In any case, we are limited by the output resolution
    tanConeAngle = max( tanConeAngle, gTanSunAngularRadius );

    return float2( mip, tanConeAngle );
}

float2 GetConeAngleFromRoughness( float mip, float roughness )
{
    float tanConeAngle = roughness * roughness * 0.05; // TODO: tweaked to be accurate and give perf boost

    return GetConeAngleFromAngularRadius( mip, tanConeAngle );
}


// SIGMA single light

// Infinite ( directional ) light source
// X => IN_PENUMBRA
float PackPenumbra( float distanceToOccluder, float tanOfLightAngularRadius )
{
    float penumbraSize = distanceToOccluder * tanOfLightAngularRadius;
    float penumbraRadius = penumbraSize * 0.5;

    return distanceToOccluder >= HALF_MAX ? HALF_MAX : min( penumbraRadius, 32768.0 );
}





[numthreads(16, 16, 1)]
void main(uint2 pixelPos : SV_DispatchThreadId)
{


    // Pixel and sample UV
    float2 pixelUv = float2(pixelPos + 0.5) * _ScreenSize.zw;
    float2 sampleUv = pixelUv + gJitter;
    
    
    // Do not generate NANs for unused threads
    if (pixelUv.x > 1.0 || pixelUv.y > 1.0)
    {
        return;
    }

    


    //trace for positionWS
    UnityRayQuery<RAY_FLAG_SKIP_PROCEDURAL_PRIMITIVES> primaryRayQuery;
    
    float znear = _ProjectionParams.y;
    float3 nearPlanePositionWS = ComputeWorldSpacePosition(sampleUv, znear, UNITY_MATRIX_I_VP);
    float3 viewDirection = normalize(nearPlanePositionWS - _WorldSpaceCameraPos);
    
    RayDesc primaryRay;
    primaryRay.Origin = _WorldSpaceCameraPos;
    primaryRay.Direction = viewDirection;
    primaryRay.TMin = 0;
    primaryRay.TMax = FLT_INF;
    primaryRayQuery.TraceRayInline(_AccelerationStructure, 0, RAYTRACINGRENDERERFLAG_CAST_SHADOW, primaryRay);
    primaryRayQuery.Proceed();
    float shadowHitDist = primaryRayQuery.CommittedRayT();
    float3 positionWS = _WorldSpaceCameraPos + viewDirection * shadowHitDist;


    float3 normalWS = UnpackGBufferNormal(_SceneNormal[pixelPos]);

    // Evaluate the ray bias
    float rayBias = EvaluateRayTracingBias(positionWS);


    DirectionalLightData dirLight = g_DirectionalLightDatas[0];



    float3 sunT, sunB;

    GetBasis(dirLight.dir,sunT,sunB);

    UnityRayQuery < RAY_FLAG_SKIP_PROCEDURAL_PRIMITIVES > shadowQuery;
    RayDesc shadowRay;
    float2 rnd;
    rnd.x = GetBNDSequenceSample(pixelPos, gFrameIndex, 0);
    rnd.y = GetBNDSequenceSample(pixelPos, gFrameIndex, 1);

    rnd = ImportanceSampling::Cosine::GetRay(rnd).xy;
    rnd =ImportanceSampling::Uniform::GetRay(rnd).xy;
    rnd *= gTanSunAngularRadius;

    float3 sunDirection = normalize(sunT.xyz * rnd.x + sunB.xyz * rnd.y + dirLight.dir);



    shadowRay.Origin = positionWS + normalWS * rayBias;
    shadowRay.Direction = sunDirection;
    shadowRay.TMin = 0;
    shadowRay.TMax = FLT_MAX;

    shadowQuery.TraceRayInline(_AccelerationStructure, 0,
                               RAYTRACINGRENDERERFLAG_CAST_SHADOW, shadowRay);
    shadowQuery.Proceed();


    shadowHitDist = shadowQuery.CommittedRayT();


    _UnfilterShadowTexture[pixelPos] = PackPenumbra(shadowHitDist, gTanSunAngularRadius);
}
